### Open & Modify Files

##### 1. `condition`

In [29]:
import pandas as pd

## open condition file
condition = pd.read_csv('H255.csv')

## maximum columns set at 'None' to display all columns
pd.set_option('display.max_columns', None)

condition

,DUID,PID,DUPERSID,CONDN,CONDIDX,PANEL,CONDRN,AGEDIAG,CRND1,CRND2,CRND3,CRND4,CRND5,INJURY,ACCDNWRK,ICD10CDX,CCSR1X,CCSR2X,CCSR3X,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND,PERWT24F,VARSTR,VARPSU
0,2810003,101,2810003101,1,2810003101001,28,1,65,-1,-1,1,1,0,2,-1,E78,END010,-1,-1,-1,2,2,2,2,2,1,16532.17940,2062,1
1,2810003,101,2810003101,4,2810003101004,28,1,-1,-1,-1,1,0,0,2,-1,M75,MUS009,-1,-1,-1,2,2,2,1,2,2,16532.17940,2062,1
2,2810003,101,2810003101,8,2810003101008,28,1,-1,-1,-1,1,0,0,2,-1,G25,NVS006,NVS016,-1,-1,2,2,2,2,2,1,16532.17940,2062,1
3,2810003,101,2810003101,9,2810003101009,28,1,-1,-1,-1,1,1,1,2,-1,G47,NVS016,-1,-1,-1,2,2,2,2,2,1,16532.17940,2062,1
4,2810003,101,2810003101,10,2810003101010,28,2,-1,-1,-1,0,0,1,1,2,M54,MUS011,-1,-1,-1,2,2,2,1,2,2,16532.17940,2062,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67700,2930421,102,2930421102,1,2930421102001,29,2,-1,0,1,0,-1,-1,2,-1,R51,NVS010,SYM010,-1,-1,2,2,2,1,2,1,17515.06225,2065,1
67701,2930421,102,2930421102,2,2930421102002,29,3,-1,0,0,1,-1,-1,2,-1,R73,SYM018,-1,-1,-1,2,2,2,2,2,1,17515.06225,2065,1
67702,2930421,102,2930421102,3,2930421102003,29,3,-1,0,0,1,-1,-1,2,-1,E78,END010,-1,-1,-1,2,2,2,2,2,1,17515.06225,2065,1
67703,2930421,104,2930421104,1,2930421104001,29,2,-1,0,1,0,-1,-1,2,-1,-15,EYE000,-1,-1,-1,2,2,2,1,2,2,15202.02402,2065,1
67704,2930421,104,2930421104,2,2930421104002,29,2,-1,0,1,0,-1,-1,2,-1,H52,EYE009,-1,-1,-1,2,2,2,1,2,2,15202.02402,2065,1

In [30]:
condition.describe

<bound method NDFrame.describe of           DUID  PID    DUPERSID  CONDN        CONDIDX  PANEL  CONDRN  AGEDIAG  \
0      2810003  101  2810003101      1  2810003101001     28       1       65
1      2810003  101  2810003101      4  2810003101004     28       1       -1
2      2810003  101  2810003101      8  2810003101008     28       1       -1
3      2810003  101  2810003101      9  2810003101009     28       1       -1
4      2810003  101  2810003101     10  2810003101010     28       2       -1
...        ...  ...         ...    ...            ...    ...     ...      ...
67700  2930421  102  2930421102      1  2930421102001     29       2       -1
67701  2930421  102  2930421102      2  2930421102002     29       3       -1
67702  2930421  102  2930421102      3  2930421102003     29       3       -1
67703  2930421  104  2930421104      1  2930421104001     29       2       -1
67704  2930421  104  2930421104      2  2930421104002     29       2       -1

       CRND1  CRND2  CRND3  CRND4  CRND5  INJURY  ACCDNWRK ICD10CDX  CCSR1X  \
0         -1     -1      1      1      0       2        -1      E78  END010
1         -1     -1      1      0      0       2        -1      M75  MUS009
2         -1     -1      1      0      0       2        -1      G25  NVS006
3         -1     -1      1      1      1       2        -1      G47  NVS016
4         -1     -1      0      0      1       1         2      M54  MUS011
...      ...    ...    ...    ...    ...     ...       ...      ...     ...
67700      0      1      0     -1     -1       2        -1      R51  NVS010
67701      0      0      1     -1     -1       2        -1      R73  SYM018
67702      0      0      1     -1     -1       2        -1      E78  END010
67703      0      1      0     -1     -1       2        -1      -15  EYE000
67704      0      1      0     -1     -1       2        -1      H52  EYE009

       CCSR2X CCSR3X CCSR4X  HHCOND  IPCOND  OPCOND  OBCOND  ERCOND  RXCOND  \
0          -1     -1     -1       2       2       2       2       2       1
1          -1     -1     -1       2       2       2       1       2       2
2      NVS016     -1     -1       2       2       2       2       2       1
3          -1     -1     -1       2       2       2       2       2       1
4          -1     -1     -1       2       2       2       1       2       2
...       ...    ...    ...     ...     ...     ...     ...     ...     ...
67700  SYM010     -1     -1       2       2       2       1       2       1
67701      -1     -1     -1       2       2       2       2       2       1
67702      -1     -1     -1       2       2       2       2       2       1
67703      -1     -1     -1       2       2       2       1       2       2
67704      -1     -1     -1       2       2       2       1       2       2

          PERWT24F  VARSTR  VARPSU
0      16532.17940    2062       1
1      16532.17940    2062       1
2      16532.17940    2062       1
3      16532.17940    2062       1
4      16532.17940    2062       1
...            ...     ...     ...
67700  17515.06225    2065       1
67701  17515.06225    2065       1
67702  17515.06225    2065       1
67703  15202.02402    2065       1
67704  15202.02402    2065       1

[67705 rows x 29 columns]>

In [ ]:
# see what F41 values exist in condition file
condition['ICD10CDX'].astype(str)[condition['ICD10CDX'].astype(str).str.startswith('F41')].unique()

<StringArray>
['F41']
Length: 1, dtype: str

In [35]:
# filter for F41
condition_f41 = condition[condition['ICD10CDX'] == 'F41'].copy()

# remove duplicate patients using DUPERSID
condition_f41.drop_duplicates(subset = ['DUPERSID'], keep = 'first', inplace = True)

In [ ]:
# checking # of unique F41 patients using DUPERSID
# (required to have at least 500 instances)
len(condition_f41)

1899

In [40]:
condition_f41

,DUID,PID,DUPERSID,CONDN,CONDIDX,PANEL,CONDRN,AGEDIAG,CRND1,CRND2,CRND3,CRND4,CRND5,INJURY,ACCDNWRK,ICD10CDX,CCSR1X,CCSR2X,CCSR3X,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND,PERWT24F,VARSTR,VARPSU
7,2810003,101,2810003101,16,2810003101016,28,3,-1,-1,-1,1,1,1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,1,2,1,16532.179400,2062,1
26,2810013,101,2810013101,5,2810013101005,28,1,-1,-1,-1,1,1,1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,2,2,1,34347.016780,2018,5
121,2810035,101,2810035101,20,2810035101020,28,3,-1,-1,-1,1,0,0,2,-1,F41,MBD005,-1,-1,-1,2,2,2,2,2,1,16052.803320,2016,2
139,2810045,102,2810045102,3,2810045102003,28,1,-1,-1,-1,1,1,0,2,-1,F41,MBD005,-1,-1,-1,2,2,2,2,2,1,20243.848800,2021,1
155,2810048,101,2810048101,5,2810048101005,28,1,-1,-1,-1,1,0,0,2,-1,F41,MBD005,-1,-1,-1,2,2,2,2,2,1,31216.450590,2042,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67566,2930389,101,2930389101,7,2930389101007,29,1,-1,1,1,1,-1,-1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,1,2,1,43073.549930,2006,2
67586,2930389,102,2930389102,14,2930389102014,29,2,-1,0,1,1,-1,-1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,1,2,1,41483.453690,2006,2
67631,2930398,101,2930398101,7,2930398101007,29,1,-1,1,0,1,-1,-1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,2,2,1,16320.903580,2066,1
67636,2930398,102,2930398102,7,2930398102007,29,2,-1,0,1,0,-1,-1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,1,2,2,14728.545380,2066,1
67653,2930408,101,2930408101,6,2930408101006,29,1,-1,1,1,1,-1,-1,2,-1,F41,MBD005,-1,-1,-1,2,2,1,2,2,1,8128.781574,2101,2

##### 2. `consolidation`

In [38]:
consolidation = pd.read_csv('h256.csv')
consolidation

,DUID,PID,DUPERSID,PANEL,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID24,FAMIDYR,CPSFAMID,FCSZ1231,FCRP1231,RULETR31,RULETR42,RULETR53,RULETR24,RUSIZE31,RUSIZE42,RUSIZE53,RUSIZE24,RUCLAS31,RUCLAS42,RUCLAS53,RUCLAS24,FAMSZE31,FAMSZE42,FAMSZE53,FAMSZE24,FMRS1231,FAMS1231,FAMSZEYR,FAMRFPYR,REGION31,REGION42,REGION53,REGION24,REFPRS31,REFPRS42,REFPRS53,REFPRS24,RESP31,RESP42,RESP53,RESP24,PROXY31,PROXY42,PROXY53,PROXY24,INTVLANG,INTVTYPE31,INTVTYPE42,INTVTYPE53,BEGRFM31,BEGRFY31,ENDRFM31,ENDRFY31,BEGRFM42,BEGRFY42,ENDRFM42,ENDRFY42,BEGRFM53,BEGRFY53,ENDRFM53,ENDRFY53,ENDRFM24,ENDRFY24,KEYNESS,INSCOP31,INSCOP42,INSCOP53,INSCOP24,INSC1231,INSCOPE,ELGRND31,ELGRND42,ELGRND53,ELGRND24,PSTATS31,PSTATS42,PSTATS53,RURSLT31,RURSLT42,RURSLT53,AGE31X,AGE42X,AGE53X,AGE24X,AGELAST,DOBMM,DOBYY,SEX,RACEV1X,RACEV2X,RACEAX,RACEBX,RACEWX,RACETHX,HISPANX,HISPNCAT,MARRY31X,MARRY42X,MARRY53X,MARRY24X,SPOUID31,SPOUID42,SPOUID53,SPOUID24,SPOUIN31,SPOUIN42,SPOUIN53,SPOUIN24,EDUCYR,HIDEG,FTSTU31X,FTSTU42X,FTSTU53X,FTSTU24X,ACTDTY31,ACTDTY42,ACTDTY53,EVERSERVED,REFRL31X,REFRL42X,REFRL53X,REFRL24X,OTHLGSPK,WHTLGSPK,HWELLSPK,BORNUSA,YRSINUS,MOPID31X,MOPID42X,MOPID53X,DAPID31X,DAPID42X,DAPID53X,HIBPDX,HIBPAGED,BPMLDX,CHDDX,CHDAGED,ANGIDX,ANGIAGED,MIDX,MIAGED,OHRTDX,OHRTAGED,OHRTTYPE,STRKDX,STRKAGED,EMPHDX,EMPHAGED,CHBRON31,CHOLDX,CHOLAGED,CANCERDX,CABLADDR,CABREAST,CACERVIX,CACOLON,CALUNG,CALYMPH,CAMELANO,CAOTHER,CAPROSTA,CASKINNM,CASKINDK,CAUTERUS,DIABDX_M18,DIABAGED,JTPAIN31_M18,ARTHDX,ARTHTYPE,ARTHAGED,ASTHDX,ASTHAGED,ASSTIL31,ASATAK31,ASTHEP31,ASACUT31,ASMRCN31,ASPREV31,ASDALY31,ASPKFL31,ASEVFL31,ASWNFL31,ADHDADDX,ADHDAGED,COVIDEVER31,COVIDEVER53,LCEVER31,LCEVER53,COVSYMNOW31,COVSYMNOW53,COVREDABIL31,COVREDABIL53,COVID12MO31,COVID12MO53,COVMNTHX31,COVMNTHX53,COVYRDX31,COVYRDX53,RTHLTH31,RTHLTH42,RTHLTH53,MNHLTH31,MNHLTH42,MNHLTH53,IADLHP31,ADLHLP31,AIDHLP31,WLKLIM31,LFTDIF31,STPDIF31,WLKDIF31,MILDIF31,STNDIF31,BENDIF31,RCHDIF31,FNGRDF31,ACTLIM31,WRKLIM31,HSELIM31,SCHLIM31,UNABLE31,SOCLIM31,COGLIM31,DFHEAR42,DFSEE42,DFCOG42,DFWLKC42,DFDRSB42,DFERND42,ANYLMI24,CHPMED42,CHPMHB42,CHPMCN42,CHSERV42,CHSRHB42,CHSRCN42,CHLIMI42,CHLIHB42,CHLICO42,CHTHER42,CHTHHB42,CHTHCO42,CHCOUN42,CHEMPB42,CSHCN42,MESHGT42,WHNHGT42,MESWGT42,WHNWGT42,CHBMIX42,MESVIS42,EATHLT42,WHNEAT42,PHYSCL42,WHNPHY42,SAFEST42,WHNSAF42,BOOST42,WHNBST42,LAPBLT42,WHNLAP42,HELMET42,WHNHEL42,NOSMOK42,WHNSMK42,TIMALN42,LSTETH53,PHYEXE53,OFTSMK53,COVAXEVR31,COVAXEVR42,COVAXEVR53,COVAXNEW31,COVAXNEW42,COVAXNEW53,SAQELIG,ADPROX42,ADSEX42,ADAGE42_M24,ADGENH42,ADDAYA42,ADCLIM42,ADACLS42,ADWKLM42,ADEMLS42,ADMWCF42,ADPAIN42,ADPCFL42,ADENGY42,ADPRST42,ADSOCA42,ADCOMPAN42,ADLEFTOUT42,ADISOL42,ADNERV42,ADHOPE42,ADREST42,ADSAD42,ADEFRT42,ADWRTH42,K6SUM42,ADINTR42,ADDPRS42,PHQ242,ADSLEEP42,ADDAYEXER42,ADMINSEXER42,ADASKALC42,ADNUMDRK42,ADRNK542_M24,ADRNK442_M24,ADOFTALC42,ADSTAL42,ADMNTRT42,ADUNABTRT42,ADPROBTRT42,ADTRTEXP42,ADBRTC42,ADMDVT42,ADFLST42,ADWGHD42,ADWTAD42,ADTBAC42,ADOFTB42,ADQTTB42,ADQTMD42,ADQTHP42,ADMOOD42,ADBPCK42,ADCHLC42,ADPNEU42_M24,ADSHNG42_M24,ADNOAP42_M24,ADDSCU42_M24,ADCOLN42_M24,ADCLNS42_M24,ADSGMD42_M24,ADBLDS42_M24,ADPROS42_M24,ADPSAG42_M24,ADUTRM42,ADPAP42,ADPAPG42,ADOSTP42_M24,ADBNDN42_M24,ADBRST42_M24,ADMMGR42_M24,VPCS42,VMCS42,VRFLAG42,ADCMPM42,ADCMPY42,ADLANG42,ADBMI42,CSAQELIG,CSLANG42,CCNRDI42,CDIAG42,CTRTMT42,CLSTRT42,CBCK42,CBCKYR42,CFTRT42,CWRKP42,CEXTM42,CWRKLV42,CNPTLD42,CWRKQT42,CNGFLX42,CPROM42,CERET42,CDLRET42,CWKLIM42,CEWRDT42,CESHTD42,CETIME42,CEBRKS42,CEDUTY42,CESKLL42,CERHAB42,CEWRHM42,CEOTHR42,CENOND42,CENONE42,CENAPP42,CDNHLP42,CJWAGE42,CJFIRE42,CJPROM42,CJDUTY42,CJNONE42,CLPROD42,CFRET42,CLHINS42,CSLHIN42_M24,CNCMED42,CNCTRP42,CNCLOD42,CNCCHD42,CNCHME42,CNCNON42,CNCNTS42,CFNDBT42,CFNAMT42,CFNVAC42,CFNPUR42,CFNSPD42,CFNSAV42,CFNLIV42,CFNOTH42,CFNONE42,CFNUNB42,CFNPMT42,CFNSTB42,CFNINC42,CDLPRS42,CDLVST42,CDLTRT42,CDLFUP42,CDLMNT42,CDLOTH42,CDLNONE42,CMCPSY42,CMCTRL42,CMCOST42,CMCWRK42,CMCFUP42,CMCEFF42,CMCSTY42,CMCTRT42,CCOGIM42,CCNEUR42,CCFATG42,CCNAUS42,CCPAIN42,CCMOTH42,CCOTHR42,CANRDX42,CFCARE42,CFRCUR42,CFTREMT42,CFOTHH42,CFTRSE42,CFPHYS42,CFSCRN42,CFREFR42,CFOTHR42,CPLSTN42,CPEXPL42,CPRESP42,CPTIME42,CPSPCP42,CPSONC42,CPSRAD42,CPSURG42,CPSOBG42,CPSDEN42,CPSOTH42,CPSDKN42,CPSYCH42,CNCAND42,CNCPND42,CNCOST42,CNCINS42,CNCACS42,CNCANX42,CNCTSP42,CNCDKN42,CNCOTH42,CEFACT42,CEFLCT42,CEFOG42,CEFMTL42,CEFUND42,CEFBCK42,CEFSTG42,CEFCOP42,CEFPOS42,CEFHLT42,CEFPHL42,CEFPAC42,CEFPIN42,CEFFTG42,CEFQLF42,CEFMHL42,CEFRLT42,CEFMPR42,CFDSKP42,CFDLST42,CFDBAL42,CWRRET42,CWRBIL42,CWRHOU42,CHPBED42,CHPDOC42,CHPCHO42,CHPERR42,CSAQPROXY42,CSCMPM42,CSCMPY42,DDNWRK24_M24,OTHNDD24_M24,FSOUT42,FSLAST42,FSAFRD42,FSSKIP42,FSSKDY42,FSLESS42,FSHGRY42,FSWTLS42,FSNEAT42,FSNEDY42,FWRENT42,FWUTIL42,FWCRED42,FWDEBT42,FWUNEXP42,ESAQELIG,EQMOBI53,EQSELF53,EQACTI53,EQPAIN53,EQDEPR53,EQVAS53,EQMVAM53,EQMVPER53,EQOVAM53,EQOVPER53,EQMBAM53,EQMBPER53,EQPPAM53,EQPPPER53,EQDENY53,EQPAYB53,EQSLEI53,EQSBIG53,EQSBAS53,EQSSAV53,EQSLIV53,EQSOTH53,EQSNON53,EQWRKP53,EQENOND53,EQEHLPWR53,EQESHRT53,EQETIME53,EQEBRKS53,EQEDUTY53,EQESKLL53,EQERHAB53,EQEWFH53,EQEOTHR53,EQENOHLP53,EQESLFEMP53,EQFRHP53,EQWINS53,EQWSIK53,EQLWLD53,EQLSAV53,EQLDEN53,EQLUPD53,EQLENH53,EQLJBSC53,EQLSIN53,EQLVOT53,EQEMP753,EQPROD53,EQACTV53,EQCARE53,EQCRRL53,EQCRLV53,EQCRLG53,EQPERS53,EQTASK53,EQALON53,EQCRNW53,EQTIME53,ESAQPROXY53,ESAQMODE53,EQCMPM53,EQCMPY53,ACCELI42,HAVEUS42,PRACTP42,YNOUSC42_M18,PROVTY42_M18,PLCTYP42,TMTKUS42,TYPEPE42,LOCATN42,PHNREG42,OFFHOU42,AFTHOU42,TREATM42,DECIDE42,EXPLOP42,PRVSPK42,DLAYCA42,AFRDCA42,DLAYDN42,AFRDDN42,DLAYPM42,AFRDPM42,EMPST31,EMPST42,EMPST53,RNDFLG31,MORJOB31,MORJOB42,MORJOB53,EVRWRK,HRWG31X,HRWG42X,HRWG53X,HRWGIM31,HRWGIM42,HRWGIM53,HRHOW31,HRHOW42,HRHOW53,DIFFWG31,DIFFWG42,DIFFWG53,NHRWGRND31,NHRWGRND42,NHRWGRND53,NHRWG31_M23,NHRWG42_M23,NHRWG53_M23,HOUR31,HOUR42,HOUR53,TEMPJB31,TEMPJB42,TEMPJB53,SSNLJB31,SSNLJB42,SSNLJB53,SELFCM31,SELFCM42,SELFCM53,DISVW31X,DISVW42X,DISVW53X,CHOIC31,CHOIC42,CHOIC53,INDCAT31_17,INDCAT42_17,INDCAT53_17,NUMEMP31,NUMEMP42,NUMEMP53,MORE31,MORE42,MORE53,UNION31,UNION42,UNION53,NWK31,NWK42,NWK53,CHGJ3142,CHGJ4253,YCHJ3142,YCHJ4253,STJBMM31,STJBYY31,STJBMM42,STJBYY42,STJBMM53,STJBYY53,EVRETIRE,OCCCAT31_18,OCCCAT42_18,OCCCAT53_18,PAYVAC31,PAYVAC42,PAYVAC53,SICPAY31,SICPAY42,SICPAY53,PAYDR31,PAYDR42,PAYDR53,RETPLN31,RETPLN42,RETPLN53,BSNTY31,BSNTY42,BSNTY53,JOBORG31,JOBORG42,JOBORG53,HELD31X,HELD42X,HELD53X,OFFER31X,OFFER42X,OFFER53X,OFREMP31,OFREMP42,OFREMP53,OUTFLAG31,OUTFLAG42,OUTFLAG53,EMPST31H,EMPST42H,EMPST53H,SLFCM31H,SLFCM42H,SLFCM53H,NMEMP31H,NMEMP42H,NMEMP53H,MORE31H,MORE42H,MORE53H,INDCT31H_17,INDCT42H_17,INDCT53H_17,OCCCT31H_18,OCCCT42H_18,OCCCT53H_18,HOUR31H,HOUR42H,HOUR53H,JBORG31H,JBORG42H,JBORG53H,UNION31H,UNION42H,UNION53H,BSNTY31H,BSNTY42H,BSNTY53H,HRWG31H,HRWG42H,HRWG53H,CMJHLD31,CMJHLD42,CMJHLD53,OFFER31H,OFFER42H,OFFER53H,OFEMP31H,OFEMP42H,OFEMP53H,PYVAC31H,PYVAC42H,PYVAC53H,SCPAY31H,SCPAY42H,SCPAY53H,PAYDR31H,PAYDR42H,PAYDR53H,RTPLN31H,RTPLN42H,RTPLN53H,FILEDR24,WILFIL24,FLSTAT24,FILER24,JTINRU24,JNTPID24,TAXFRM24,FOODST24,FOODMN24,FOODVL24,TTLP24X,FAMINC24,POVCAT24,POVLEV24,WAGEP24X,WAGIMP24,BUSNP24X,BUSIMP24,UNEMP24X,UNEIMP24,WCMPP24X,WCPIMP24,INTRP24X,INTIMP24,DIVDP24X,DIVIMP24,SALEP24X,SALIMP24,PENSP24X,PENIMP24,SSECP24X,SSCIMP24,TRSTP24X,TRTIMP24,VETSP24X,VETIMP24,IRASP24X,IRAIMP24,ALIMP24X,ALIIMP24,CHLDP24X,CHLIMP24,CASHP24X,CSHIMP24,SSIP24X,SSIIMP24,PUBP24X,PUBIMP24,OTHRP24X,OTHIMP24,HIEUIDX,TRIJA24X,TRIFE24X,TRIMA24X,TRIAP24X,TRIMY24X,TRIJU24X,TRIJL24X,TRIAU24X,TRISE24X,TRIOC24X,TRINO24X,TRIDE24X,MCRJA24,MCRFE24,MCRMA24,MCRAP24,MCRMY24,MCRJU24,MCRJL24,MCRAU24,MCRSE24,MCROC24,MCRNO24,MCRDE24,MCRJA24X,MCRFE24X,MCRMA24X,MCRAP24X,MCRMY24X,MCRJU24X,MCRJL24X,MCRAU24X,MCRSE24X,MCROC24X,MCRNO24X,MCRDE24X,MCDJA24,MCDFE24,MCDMA24,MCDAP24,MCDMY24,MCDJU24,MCDJL24,MCDAU24,MCDSE24,MCDOC24,MCDNO24,MCDDE24,MCDJA24X,MCDFE24X,MCDMA24X,MCDAP24X,MCDMY24X,MCDJU24X,MCDJL24X,MCDAU24X,MCDSE24X,MCDOC24X,MCDNO24X,MCDDE24X,GVAJA24,GVAFE24,GVAMA24,GVAAP24,GVAMY24,GVAJU24,GVAJL24,GVAAU24,GVASE24,GVAOC24,GVANO24,GVADE24,GVBJA24,GVBFE24,GVBMA24,GVBAP24,GVBMY24,GVBJU24,GVBJL24,GVBAU24,GVBSE24,GVBOC24,GVBNO24,GVBDE24,GVCJA24,GVCFE24,GVCMA24,GVCAP24,GVCMY24,GVCJU24,GVCJL24,GVCAU24,GVCSE24,GVCOC24,GVCNO24,GVCDE24,VAPJA24,VAPFE24,VAPMA24,VAPAP24,VAPMY24,VAPJU24,VAPJL24,VAPAU24,VAPSE24,VAPOC24,VAPNO24,VAPDE24,IHSJA24,IHSFE24,IHSMA24,IHSAP24,IHSMY24,IHSJU24,IHSJL24,IHSAU24,IHSSE24,IHSOC24,IHSNO24,IHSDE24,PUBJA24X,PUBFE24X,PUBMA24X,PUBAP24X,PUBMY24X,PUBJU24X,PUBJL24X,PUBAU24X,PUBSE24X,PUBOC24X,PUBNO24X,PUBDE24X,PEGJA24,PEGFE24,PEGMA24,PEGAP24,PEGMY24,PEGJU24,PEGJL24,PEGAU24,PEGSE24,PEGOC24,PEGNO24,PEGDE24,PDKJA24,PDKFE24,PDKMA24,PDKAP24,PDKMY24,PDKJU24,PDKJL24,PDKAU24,PDKSE24,PDKOC24,PDKNO24,PDKDE24,PNGJA24,PNGFE24,PNGMA24,PNGAP24,PNGMY24,PNGJU24,PNGJL24,PNGAU24,PNGSE24,PNGOC24,PNGNO24,PNGDE24,POGJA24,POGFE24,POGMA24,POGAP24,POGMY24,POGJU24,POGJL24,POGAU24,POGSE24,POGOC24,POGNO24,POGDE24,POEJA24,POEFE24,POEMA24,POEAP24,POEMY24,POEJU24,POEJL24,POEAU24,POESE24,POEOC24,POENO24,POEDE24,PNEJA24,PNEFE24,PNEMA24,PNEAP24,PNEMY24,PNEJU24,PNEJL24,PNEAU24,PNESE24,PNEOC24,PNENO24,PNEDE24,PRXJA24,PRXFE24,PRXMA24,PRXAP24,PRXMY24,PRXJU24,PRXJL24,PRXAU24,PRXSE24,PRXOC24,PRXNO24,PRXDE24,PRIJA24,PRIFE24,PRIMA24,PRIAP24,PRIMY24,PRIJU24,PRIJL24,PRIAU24,PRISE24,PRIOC24,PRINO24,PRIDE24,HPEJA24,HPEFE24,HPEMA24,HPEAP24,HPEMY24,HPEJU24,HPEJL24,HPEAU24,HPESE24,HPEOC24,HPENO24,HPEDE24,HPDJA24,HPDFE24,HPDMA24,HPDAP24,HPDMY24,HPDJU24,HPDJL24,HPDAU24,HPDSE24,HPDOC24,HPDNO24,HPDDE24,HPNJA24,HPNFE24,HPNMA24,HPNAP24,HPNMY24,HPNJU24,HPNJL24,HPNAU24,HPNSE24,HPNOC24,HPNNO24,HPNDE24,HPOJA24,HPOFE24,HPOMA24,HPOAP24,HPOMY24,HPOJU24,HPOJL24,HPOAU24,HPOSE24,HPOOC24,HPONO24,HPODE24,HPXJA24,HPXFE24,HPXMA24,HPXAP24,HPXMY24,HPXJU24,HPXJL24,HPXAU24,HPXSE24,HPXOC24,HPXNO24,HPXDE24,HPRJA24,HPRFE24,HPRMA24,HPRAP24,HPRMY24,HPRJU24,HPRJL24,HPRAU24,HPRSE24,HPROC24,HPRNO24,HPRDE24,INSJA24X,INSFE24X,INSMA24X,INSAP24X,INSMY24X,INSJU24X,INSJL24X,INSAU24X,INSSE24X,INSOC24X,INSNO24X,INSDE24X,PRVEV24,TRIEV24,MCREV24,MCDEV24,VAEV24,GVAEV24,GVBEV24,GVCEV24,UNINS24,INSCOV24,INSURC24,TRICH31X,TRICH42X,TRICH24X,TRI31X,TRI42X,TRI24X,MCRPHD31,MCRPHD42,MCRPHD24,MCRPD31,MCRPD42,MCRPD24,MCRPD31X,MCRPD42X,MCRPD24X,MCRPHO31,MCRPHO42,MCRPHO24,MCDHMO31,MCDHMO42,MCDHMO24,MCDMC31,MCDMC42,MCDMC24,PRVHMO31_M23,PRVHMO42_M23,PRVHMO24_M23,FSAGT31,HASFSA31,PFSAMT31,PREVCOVR,MORECOVR,TRICR31X,TRICR42X,TRICR53X,TRICR24X,TRIAT31X,TRIAT42X,TRIAT53X,TRIAT24X,MCAID31,MCAID42,MCAID53,MCAID24,MCAID31X,MCAID42X,MCAID53X,MCAID24X,MCARE31,MCARE42,MCARE53,MCARE24,MCARE31X,MCARE42X,MCARE53X,MCARE24X,MCDAT31X,MCDAT42X,MCDAT53X,MCDAT24X,GOVTA31,GOVTA42,GOVTA53,GOVTA24,GOVAAT31,GOVAAT42,GOVAAT53,GOVAAT24,GOVTB31,GOVTB42,GOVTB53,GOVTB24,GOVBAT31,GOVBAT42,GOVBAT53,GOVBAT24,GOVTC31,GOVTC42,GOVTC53,GOVTC24,GOVCAT31,GOVCAT42,GOVCAT53,GOVCAT24,VAPROG31,VAPROG42,VAPROG53,VAPROG24,VAPRAT31,VAPRAT42,VAPRAT53,VAPRAT24,IHS31,IHS42,IHS53,IHS24,IHSAT31,IHSAT42,IHSAT53,IHSAT24,PRIDK31,PRIDK42,PRIDK53,PRIDK24,PRIEU31,PRIEU42,PRIEU53,PRIEU24,PRING31,PRING42,PRING53,PRING24,PRIOG31,PRIOG42,PRIOG53,PRIOG24,PRINEO31,PRINEO42,PRINEO53,PRINEO24,PRIEUO31,PRIEUO42,PRIEUO53,PRIEUO24,PRSTX31,PRSTX42,PRSTX53,PRSTX24,PRIV31,PRIV42,PRIV53,PRIV24,PRIVAT31,PRIVAT42,PRIVAT53,PRIVAT24,PUB31X,PUB42X,PUB53X,PUB24X,PUBAT31X,PUBAT42X,PUBAT53X,PUBAT24X,VERFLG31,VERFLG42,VERFLG24,INS31X,INS42X,INS53X,INS24X,INSAT31X,INSAT42X,INSAT53X,INSAT24X,DENTIN31_M23,DENTIN42_M23,DENTIN53_M23,DNTINS31_M23,DNTINS24_M23,PMEDIN31,PMEDIN42,PMEDIN53,PMDINS31,PMDINS24,PROBPY42,CRFMPY42,PYUNBL42,MEDDEBT42,PMEDUP31,PMEDUP42,PMEDUP53,PMEDPY31,PMEDPY42,PMEDPY53,TOTTCH24,TOTEXP24,TOTSLF24,TOTMCR24,TOTMCD24,TOTPRV24,TOTVA24,TOTTRI24,TOTOFD24,TOTSTL24,TOTWCP24,TOTOSR24,TOTPTR24,TOTOTH24,OBTOTV24,OBVTCH24,OBVEXP24,OBVSLF24,OBVMCR24,OBVMCD24,OBVPRV24,OBVVA24,OBVTRI24,OBVOFD24,OBVSTL24,OBVWCP24,OBVOSR24,OBVPTR24,OBVOTH24,OBDRV24,OBDTCH24,OBDEXP24,OBDSLF24,OBDMCR24,OBDMCD24,OBDPRV24,OBDVA24,OBDTRI24,OBDOFD24,OBDSTL24,OBDWCP24,OBDOSR24,OBDPTR24,OBDOTH24,OPTOTV24,OPTTCH24,OPTEXP24,OPTSLF24,OPTMCR24,OPTMCD24,OPTPRV24,OPTVA24,OPTTRI24,OPTOFD24,OPTSTL24,OPTWCP24,OPTOSR24,OPTPTR24,OPTOTH24,OPFTCH24,OPFEXP24,OPFSLF24,OPFMCR24,OPFMCD24,OPFPRV24,OPFVA24,OPFTRI24,OPFOFD24,OPFSTL24,OPFWCP24,OPFOSR24,OPFPTR24,OPFOTH24,OPDEXP24,OPDTCH24,OPDSLF24,OPDMCR24,OPDMCD24,OPDPRV24,OPDVA24,OPDTRI24,OPDOFD24,OPDSTL24,OPDWCP24,OPDOSR24,OPDPTR24,OPDOTH24,OPDRV24,OPVTCH24,OPVEXP24,OPVSLF24,OPVMCR24,OPVMCD24,OPVPRV24,OPVVA24,OPVTRI24,OPVOFD24,OPVSTL24,OPVWCP24,OPVOSR24,OPVPTR24,OPVOTH24,OPSEXP24,OPSTCH24,OPSSLF24,OPSMCR24,OPSMCD24,OPSPRV24,OPSVA24,OPSTRI24,OPSOFD24,OPSSTL24,OPSWCP24,OPSOSR24,OPSPTR24,OPSOTH24,ERTOT24,ERTTCH24,ERTEXP24,ERTSLF24,ERTMCR24,ERTMCD24,ERTPRV24,ERTVA24,ERTTRI24,ERTOFD24,ERTSTL24,ERTWCP24,ERTOSR24,ERTPTR24,ERTOTH24,ERFTCH24,ERFEXP24,ERFSLF24,ERFMCR24,ERFMCD24,ERFPRV24,ERFVA24,ERFTRI24,ERFOFD24,ERFSTL24,ERFWCP24,ERFOSR24,ERFPTR24,ERFOTH24,ERDEXP24,ERDTCH24,ERDSLF24,ERDMCR24,ERDMCD24,ERDPRV24,ERDVA24,ERDTRI24,ERDOFD24,ERDSTL24,ERDWCP24,ERDOSR24,ERDPTR24,ERDOTH24,IPDIS24,IPTEXP24,IPTTCH24,IPTSLF24,IPTMCR24,IPTMCD24,IPTPRV24,IPTVA24,IPTTRI24,IPTOFD24,IPTSTL24,IPTWCP24,IPTOSR24,IPTPTR24,IPTOTH24,IPFEXP24,IPFTCH24,IPFSLF24,IPFMCR24,IPFMCD24,IPFPRV24,IPFVA24,IPFTRI24,IPFOFD24,IPFSTL24,IPFWCP24,IPFOSR24,IPFPTR24,IPFOTH24,IPDEXP24,IPDTCH24,IPDSLF24,IPDMCR24,IPDMCD24,IPDPRV24,IPDVA24,IPDTRI24,IPDOFD24,IPDSTL24,IPDWCP24,IPDOSR24,IPDPTR24,IPDOTH24,IPNGTD24,DVTOT24,DVTTCH24,DVTEXP24,DVTSLF24,DVTMCR24,DVTMCD24,DVTPRV24,DVTVA24,DVTTRI24,DVTOFD24,DVTSTL24,DVTWCP24,DVTOSR24,DVTPTR24,DVTOTH24,HHTOTD24,HHAGD24,HHATCH24,HHAEXP24,HHASLF24,HHAMCR24,HHAMCD24,HHAPRV24,HHAVA24,HHATRI24,HHAOFD24,HHASTL24,HHAWCP24,HHAOSR24,HHAPTR24,HHAOTH24,HHINDD24,HHNTCH24,HHNEXP24,HHNSLF24,HHNMCD24,HHNMCR24,HHNPRV24,HHNVA24,HHNTRI24,HHNOFD24,HHNSTL24,HHNWCP24,HHNOSR24,HHNPTR24,HHNOTH24,HHINFD24,VISEXP24,VISTCH24,VISSLF24,VISMCR24,VISMCD24,VISPRV24,VISVA24,VISTRI24,VISOFD24,VISSTL24,VISWCP24,VISOSR24,VISPTR24,VISOTH24,OTHTCH24,OTHEXP24,OTHSLF24,OTHMCR24,OTHMCD24,OTHPRV24,OTHVA24,OTHTRI24,OTHOFD24,OTHSTL24,OTHWCP24,OTHOSR24,OTHPTR24,OTHOTH24,RXTOT24,RXEXP24,RXSLF24,RXMCR24,RXMCD24,RXPRV24,RXVA24,RXTRI24,RXOFD24,RXSTL24,RXWCP24,RXOSR24,RXPTR24,RXOTH24,PERWT24F,FAMWT24F,FAMWT24C,VARSTR,VARPSU,SAQWT24F,CSAQW24F,ESAQWT24F,PESAQWT24F
0,2810003,101,2810003101,28,2024,A,A,A,A,A,A,1,1,A,A,A,A,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,4,4,4,101,101,101,101,1,1,1,1,1,1,1,1,1,1,2,2,8,2023,2,2024,2,2024,11,2024,11,2024,12,2024,12,2024,1,1,1,1,1,1,1,1,1,1,1,11,11,11,60,60,60,66,67,67,67,67,3,1957,2,1,1,3,3,1,2,2,9,2,2,2,2,995,995,995,995,2,2,2,2,12,3,-1,-1,-1,-1,4,4,4,2,1,1,1,1,2,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,2,-1,2,-1,2,-1,1,30,6,2,-1,2,-1,2,1,65,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,1,3,55,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,3,3,3,3,4,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.00,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,3,1,1,1,2,2,2,1,1,2,4,3,2,2,2,2,1,1,4,2,4,5,4,3,3,2,2,1,2,0,1,1,7,1,1,2,3,1,1,6,1,1,1,1,2,2,1,4,2,2,1,1,1,2,1,3,-1,-1,-1,1,1,1,1,3,2,1,2,1,3,1,-1,-1,2,1,5,1,-1,2,1,36.70,51.30,0,7,2024,1,18.29,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,3,3,3,-1,-1,-1,-1,-1,-1,-1,2,2,2,2,4,1,1,1,1,4,3,61,520.0,1,0.0,3,12.0,2,52.0,1,1,6,2,2,2,2,2,2,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5,2,-1,-1,-1,-1,-1,-1,-1,-1,1,2,2,2025,1,1,2,-1,1,3,2,-1,1,3,1,3,1,4,1,-1,2,2,1,2,2,2,1,3,4,2,2,-1,-1,-1,14.00,-1.0,-1.0,0,0,0,3,-1,-1,1,-1,-1,3,-1,-1,15.25,-1.0,-1.0,16,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,1,-1,-1,-8,-1,-1,5,-1,-1,100,-1,-1,1,-1,-1,2,-1,-1,-1,-1,6,3,-1,7,-1,2,2023,-1,-1,-1,-1,1,8,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,-1,-1,-1,1,-1,-1,2,-1,-1,-15,-1,-1,-15,-1,-1,-1,-1,-1,1,34,34,2,-1,-1,100,-1,-1,1,-1,-1,5,-1,-1,8,-1,-1,16,-1,-1,1,-1,-1,2,-1,-1,-1,-1,-1,15.25,-1.00,-1.00,2,-1,-1,1,-1,-1,1,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,1,1,1,-1,-1,1,2,-1,-1,82732,82732,5,549.90,3416,4,0,1,0,1,0,1,50716,6,2000,1,175529,1,5000,1,21600,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,2810003A1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,2,2,2,2,2,2,2,4,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,2,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,95,95,95,1,1,1,1,1,1,1,1,1,1,2,1,2,2,2,2,2,2,2,1,-1,1,1,1,1,1,1,1,56703,12912,2751,10161,0,0,0,0,0,0,0,0,0,0,14,5501,2347,618,1729,0,0,0,0,0,0,0,0,0,0,6,3851,1646,355,1291,0,0,0,0,0,0,0,0,0,0,1,5005,507,150,357,0,0,0,0,0,0,0,0,0,0,2000,428,150,278,0,0,0,0,0,0,0,0,0,0,79,3005,0,79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,36000,6245,1475,4770,0,0,0,0,0,0,0,0,0,0,36000,6245,1475,4770,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,899,5581,0,899,0,0,0,0,0,0,0,0,0,0,177,1554,0,177,0,0,0,0,0,0,0,0,0,0,722,4027,0,722,0,0,0,0,0,0,0,0,0,0,1,5,2380,973,0,973,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,210,210,210,0,0,0,0,0,0,0,0,0,0,0,2026,1533,275,1258,0,0,0,0,0,0,0,0,0,0,17,198,23,175,0,0,0,0,0,0,0,0,0,0,16532.17940,14481.89179,14481.89179,2062,1,19220.25904,0.0,19419.84514,22951.57530

### Joining `condition` & `consolidation` files

In [41]:
joined = pd.merge(left = consolidation, right = condition_f41 , how = 'inner', on = 'DUPERSID')
joined

,DUID_x,PID_x,DUPERSID,PANEL_x,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID24,FAMIDYR,CPSFAMID,FCSZ1231,FCRP1231,RULETR31,RULETR42,RULETR53,RULETR24,RUSIZE31,RUSIZE42,RUSIZE53,RUSIZE24,RUCLAS31,RUCLAS42,RUCLAS53,RUCLAS24,FAMSZE31,FAMSZE42,FAMSZE53,FAMSZE24,FMRS1231,FAMS1231,FAMSZEYR,FAMRFPYR,REGION31,REGION42,REGION53,REGION24,REFPRS31,REFPRS42,REFPRS53,REFPRS24,RESP31,RESP42,RESP53,RESP24,PROXY31,PROXY42,PROXY53,PROXY24,INTVLANG,INTVTYPE31,INTVTYPE42,INTVTYPE53,BEGRFM31,BEGRFY31,ENDRFM31,ENDRFY31,BEGRFM42,BEGRFY42,ENDRFM42,ENDRFY42,BEGRFM53,BEGRFY53,ENDRFM53,ENDRFY53,ENDRFM24,ENDRFY24,KEYNESS,INSCOP31,INSCOP42,INSCOP53,INSCOP24,INSC1231,INSCOPE,ELGRND31,ELGRND42,ELGRND53,ELGRND24,PSTATS31,PSTATS42,PSTATS53,RURSLT31,RURSLT42,RURSLT53,AGE31X,AGE42X,AGE53X,AGE24X,AGELAST,DOBMM,DOBYY,SEX,RACEV1X,RACEV2X,RACEAX,RACEBX,RACEWX,RACETHX,HISPANX,HISPNCAT,MARRY31X,MARRY42X,MARRY53X,MARRY24X,SPOUID31,SPOUID42,SPOUID53,SPOUID24,SPOUIN31,SPOUIN42,SPOUIN53,SPOUIN24,EDUCYR,HIDEG,FTSTU31X,FTSTU42X,FTSTU53X,FTSTU24X,ACTDTY31,ACTDTY42,ACTDTY53,EVERSERVED,REFRL31X,REFRL42X,REFRL53X,REFRL24X,OTHLGSPK,WHTLGSPK,HWELLSPK,BORNUSA,YRSINUS,MOPID31X,MOPID42X,MOPID53X,DAPID31X,DAPID42X,DAPID53X,HIBPDX,HIBPAGED,BPMLDX,CHDDX,CHDAGED,ANGIDX,ANGIAGED,MIDX,MIAGED,OHRTDX,OHRTAGED,OHRTTYPE,STRKDX,STRKAGED,EMPHDX,EMPHAGED,CHBRON31,CHOLDX,CHOLAGED,CANCERDX,CABLADDR,CABREAST,CACERVIX,CACOLON,CALUNG,CALYMPH,CAMELANO,CAOTHER,CAPROSTA,CASKINNM,CASKINDK,CAUTERUS,DIABDX_M18,DIABAGED,JTPAIN31_M18,ARTHDX,ARTHTYPE,ARTHAGED,ASTHDX,ASTHAGED,ASSTIL31,ASATAK31,ASTHEP31,ASACUT31,ASMRCN31,ASPREV31,ASDALY31,ASPKFL31,ASEVFL31,ASWNFL31,ADHDADDX,ADHDAGED,COVIDEVER31,COVIDEVER53,LCEVER31,LCEVER53,COVSYMNOW31,COVSYMNOW53,COVREDABIL31,COVREDABIL53,COVID12MO31,COVID12MO53,COVMNTHX31,COVMNTHX53,COVYRDX31,COVYRDX53,RTHLTH31,RTHLTH42,RTHLTH53,MNHLTH31,MNHLTH42,MNHLTH53,IADLHP31,ADLHLP31,AIDHLP31,WLKLIM31,LFTDIF31,STPDIF31,WLKDIF31,MILDIF31,STNDIF31,BENDIF31,RCHDIF31,FNGRDF31,ACTLIM31,WRKLIM31,HSELIM31,SCHLIM31,UNABLE31,SOCLIM31,COGLIM31,DFHEAR42,DFSEE42,DFCOG42,DFWLKC42,DFDRSB42,DFERND42,ANYLMI24,CHPMED42,CHPMHB42,CHPMCN42,CHSERV42,CHSRHB42,CHSRCN42,CHLIMI42,CHLIHB42,CHLICO42,CHTHER42,CHTHHB42,CHTHCO42,CHCOUN42,CHEMPB42,CSHCN42,MESHGT42,WHNHGT42,MESWGT42,WHNWGT42,CHBMIX42,MESVIS42,EATHLT42,WHNEAT42,PHYSCL42,WHNPHY42,SAFEST42,WHNSAF42,BOOST42,WHNBST42,LAPBLT42,WHNLAP42,HELMET42,WHNHEL42,NOSMOK42,WHNSMK42,TIMALN42,LSTETH53,PHYEXE53,OFTSMK53,COVAXEVR31,COVAXEVR42,COVAXEVR53,COVAXNEW31,COVAXNEW42,COVAXNEW53,SAQELIG,ADPROX42,ADSEX42,ADAGE42_M24,ADGENH42,ADDAYA42,ADCLIM42,ADACLS42,ADWKLM42,ADEMLS42,ADMWCF42,ADPAIN42,ADPCFL42,ADENGY42,ADPRST42,ADSOCA42,ADCOMPAN42,ADLEFTOUT42,ADISOL42,ADNERV42,ADHOPE42,ADREST42,ADSAD42,ADEFRT42,ADWRTH42,K6SUM42,ADINTR42,ADDPRS42,PHQ242,ADSLEEP42,ADDAYEXER42,ADMINSEXER42,ADASKALC42,ADNUMDRK42,ADRNK542_M24,ADRNK442_M24,ADOFTALC42,ADSTAL42,ADMNTRT42,ADUNABTRT42,ADPROBTRT42,ADTRTEXP42,ADBRTC42,ADMDVT42,ADFLST42,ADWGHD42,ADWTAD42,ADTBAC42,ADOFTB42,ADQTTB42,ADQTMD42,ADQTHP42,ADMOOD42,ADBPCK42,ADCHLC42,ADPNEU42_M24,ADSHNG42_M24,ADNOAP42_M24,ADDSCU42_M24,ADCOLN42_M24,ADCLNS42_M24,ADSGMD42_M24,ADBLDS42_M24,ADPROS42_M24,ADPSAG42_M24,ADUTRM42,ADPAP42,ADPAPG42,ADOSTP42_M24,ADBNDN42_M24,ADBRST42_M24,ADMMGR42_M24,VPCS42,VMCS42,VRFLAG42,ADCMPM42,ADCMPY42,ADLANG42,ADBMI42,CSAQELIG,CSLANG42,CCNRDI42,CDIAG42,CTRTMT42,CLSTRT42,CBCK42,CBCKYR42,CFTRT42,CWRKP42,CEXTM42,CWRKLV42,CNPTLD42,CWRKQT42,CNGFLX42,CPROM42,CERET42,CDLRET42,CWKLIM42,CEWRDT42,CESHTD42,CETIME42,CEBRKS42,CEDUTY42,CESKLL42,CERHAB42,CEWRHM42,CEOTHR42,CENOND42,CENONE42,CENAPP42,CDNHLP42,CJWAGE42,CJFIRE42,CJPROM42,CJDUTY42,CJNONE42,CLPROD42,CFRET42,CLHINS42,CSLHIN42_M24,CNCMED42,CNCTRP42,CNCLOD42,CNCCHD42,CNCHME42,CNCNON42,CNCNTS42,CFNDBT42,CFNAMT42,CFNVAC42,CFNPUR42,CFNSPD42,CFNSAV42,CFNLIV42,CFNOTH42,CFNONE42,CFNUNB42,CFNPMT42,CFNSTB42,CFNINC42,CDLPRS42,CDLVST42,CDLTRT42,CDLFUP42,CDLMNT42,CDLOTH42,CDLNONE42,CMCPSY42,CMCTRL42,CMCOST42,CMCWRK42,CMCFUP42,CMCEFF42,CMCSTY42,CMCTRT42,CCOGIM42,CCNEUR42,CCFATG42,CCNAUS42,CCPAIN42,CCMOTH42,CCOTHR42,CANRDX42,CFCARE42,CFRCUR42,CFTREMT42,CFOTHH42,CFTRSE42,CFPHYS42,CFSCRN42,CFREFR42,CFOTHR42,CPLSTN42,CPEXPL42,CPRESP42,CPTIME42,CPSPCP42,CPSONC42,CPSRAD42,CPSURG42,CPSOBG42,CPSDEN42,CPSOTH42,CPSDKN42,CPSYCH42,CNCAND42,CNCPND42,CNCOST42,CNCINS42,CNCACS42,CNCANX42,CNCTSP42,CNCDKN42,CNCOTH42,CEFACT42,CEFLCT42,CEFOG42,CEFMTL42,CEFUND42,CEFBCK42,CEFSTG42,CEFCOP42,CEFPOS42,CEFHLT42,CEFPHL42,CEFPAC42,CEFPIN42,CEFFTG42,CEFQLF42,CEFMHL42,CEFRLT42,CEFMPR42,CFDSKP42,CFDLST42,CFDBAL42,CWRRET42,CWRBIL42,CWRHOU42,CHPBED42,CHPDOC42,CHPCHO42,CHPERR42,CSAQPROXY42,CSCMPM42,CSCMPY42,DDNWRK24_M24,OTHNDD24_M24,FSOUT42,FSLAST42,FSAFRD42,FSSKIP42,FSSKDY42,FSLESS42,FSHGRY42,FSWTLS42,FSNEAT42,FSNEDY42,FWRENT42,FWUTIL42,FWCRED42,FWDEBT42,FWUNEXP42,ESAQELIG,EQMOBI53,EQSELF53,EQACTI53,EQPAIN53,EQDEPR53,EQVAS53,EQMVAM53,EQMVPER53,EQOVAM53,EQOVPER53,EQMBAM53,EQMBPER53,EQPPAM53,EQPPPER53,EQDENY53,EQPAYB53,EQSLEI53,EQSBIG53,EQSBAS53,EQSSAV53,EQSLIV53,EQSOTH53,EQSNON53,EQWRKP53,EQENOND53,EQEHLPWR53,EQESHRT53,EQETIME53,EQEBRKS53,EQEDUTY53,EQESKLL53,EQERHAB53,EQEWFH53,EQEOTHR53,EQENOHLP53,EQESLFEMP53,EQFRHP53,EQWINS53,EQWSIK53,EQLWLD53,EQLSAV53,EQLDEN53,EQLUPD53,EQLENH53,EQLJBSC53,EQLSIN53,EQLVOT53,EQEMP753,EQPROD53,EQACTV53,EQCARE53,EQCRRL53,EQCRLV53,EQCRLG53,EQPERS53,EQTASK53,EQALON53,EQCRNW53,EQTIME53,ESAQPROXY53,ESAQMODE53,EQCMPM53,EQCMPY53,ACCELI42,HAVEUS42,PRACTP42,YNOUSC42_M18,PROVTY42_M18,PLCTYP42,TMTKUS42,TYPEPE42,LOCATN42,PHNREG42,OFFHOU42,AFTHOU42,TREATM42,DECIDE42,EXPLOP42,PRVSPK42,DLAYCA42,AFRDCA42,DLAYDN42,AFRDDN42,DLAYPM42,AFRDPM42,EMPST31,EMPST42,EMPST53,RNDFLG31,MORJOB31,MORJOB42,MORJOB53,EVRWRK,HRWG31X,HRWG42X,HRWG53X,HRWGIM31,HRWGIM42,HRWGIM53,HRHOW31,HRHOW42,HRHOW53,DIFFWG31,DIFFWG42,DIFFWG53,NHRWGRND31,NHRWGRND42,NHRWGRND53,NHRWG31_M23,NHRWG42_M23,NHRWG53_M23,HOUR31,HOUR42,HOUR53,TEMPJB31,TEMPJB42,TEMPJB53,SSNLJB31,SSNLJB42,SSNLJB53,SELFCM31,SELFCM42,SELFCM53,DISVW31X,DISVW42X,DISVW53X,CHOIC31,CHOIC42,CHOIC53,INDCAT31_17,INDCAT42_17,INDCAT53_17,NUMEMP31,NUMEMP42,NUMEMP53,MORE31,MORE42,MORE53,UNION31,UNION42,UNION53,NWK31,NWK42,NWK53,CHGJ3142,CHGJ4253,YCHJ3142,YCHJ4253,STJBMM31,STJBYY31,STJBMM42,STJBYY42,STJBMM53,STJBYY53,EVRETIRE,OCCCAT31_18,OCCCAT42_18,OCCCAT53_18,PAYVAC31,PAYVAC42,PAYVAC53,SICPAY31,SICPAY42,SICPAY53,PAYDR31,PAYDR42,PAYDR53,RETPLN31,RETPLN42,RETPLN53,BSNTY31,BSNTY42,BSNTY53,JOBORG31,JOBORG42,JOBORG53,HELD31X,HELD42X,HELD53X,OFFER31X,OFFER42X,OFFER53X,OFREMP31,OFREMP42,OFREMP53,OUTFLAG31,OUTFLAG42,OUTFLAG53,EMPST31H,EMPST42H,EMPST53H,SLFCM31H,SLFCM42H,SLFCM53H,NMEMP31H,NMEMP42H,NMEMP53H,MORE31H,MORE42H,MORE53H,INDCT31H_17,INDCT42H_17,INDCT53H_17,OCCCT31H_18,OCCCT42H_18,OCCCT53H_18,HOUR31H,HOUR42H,HOUR53H,JBORG31H,JBORG42H,JBORG53H,UNION31H,UNION42H,UNION53H,BSNTY31H,BSNTY42H,BSNTY53H,HRWG31H,HRWG42H,HRWG53H,CMJHLD31,CMJHLD42,CMJHLD53,OFFER31H,OFFER42H,OFFER53H,OFEMP31H,OFEMP42H,OFEMP53H,PYVAC31H,PYVAC42H,PYVAC53H,SCPAY31H,SCPAY42H,SCPAY53H,PAYDR31H,PAYDR42H,PAYDR53H,RTPLN31H,RTPLN42H,RTPLN53H,FILEDR24,WILFIL24,FLSTAT24,FILER24,JTINRU24,JNTPID24,TAXFRM24,FOODST24,FOODMN24,FOODVL24,TTLP24X,FAMINC24,POVCAT24,POVLEV24,WAGEP24X,WAGIMP24,BUSNP24X,BUSIMP24,UNEMP24X,UNEIMP24,WCMPP24X,WCPIMP24,INTRP24X,INTIMP24,DIVDP24X,DIVIMP24,SALEP24X,SALIMP24,PENSP24X,PENIMP24,SSECP24X,SSCIMP24,TRSTP24X,TRTIMP24,VETSP24X,VETIMP24,IRASP24X,IRAIMP24,ALIMP24X,ALIIMP24,CHLDP24X,CHLIMP24,CASHP24X,CSHIMP24,SSIP24X,SSIIMP24,PUBP24X,PUBIMP24,OTHRP24X,OTHIMP24,HIEUIDX,TRIJA24X,TRIFE24X,TRIMA24X,TRIAP24X,TRIMY24X,TRIJU24X,TRIJL24X,TRIAU24X,TRISE24X,TRIOC24X,TRINO24X,TRIDE24X,MCRJA24,MCRFE24,MCRMA24,MCRAP24,MCRMY24,MCRJU24,MCRJL24,MCRAU24,MCRSE24,MCROC24,MCRNO24,MCRDE24,MCRJA24X,MCRFE24X,MCRMA24X,MCRAP24X,MCRMY24X,MCRJU24X,MCRJL24X,MCRAU24X,MCRSE24X,MCROC24X,MCRNO24X,MCRDE24X,MCDJA24,MCDFE24,MCDMA24,MCDAP24,MCDMY24,MCDJU24,MCDJL24,MCDAU24,MCDSE24,MCDOC24,MCDNO24,MCDDE24,MCDJA24X,MCDFE24X,MCDMA24X,MCDAP24X,MCDMY24X,MCDJU24X,MCDJL24X,MCDAU24X,MCDSE24X,MCDOC24X,MCDNO24X,MCDDE24X,GVAJA24,GVAFE24,GVAMA24,GVAAP24,GVAMY24,GVAJU24,GVAJL24,GVAAU24,GVASE24,GVAOC24,GVANO24,GVADE24,GVBJA24,GVBFE24,GVBMA24,GVBAP24,GVBMY24,GVBJU24,GVBJL24,GVBAU24,GVBSE24,GVBOC24,GVBNO24,GVBDE24,GVCJA24,GVCFE24,GVCMA24,GVCAP24,GVCMY24,GVCJU24,GVCJL24,GVCAU24,GVCSE24,GVCOC24,GVCNO24,GVCDE24,VAPJA24,VAPFE24,VAPMA24,VAPAP24,VAPMY24,VAPJU24,VAPJL24,VAPAU24,VAPSE24,VAPOC24,VAPNO24,VAPDE24,IHSJA24,IHSFE24,IHSMA24,IHSAP24,IHSMY24,IHSJU24,IHSJL24,IHSAU24,IHSSE24,IHSOC24,IHSNO24,IHSDE24,PUBJA24X,PUBFE24X,PUBMA24X,PUBAP24X,PUBMY24X,PUBJU24X,PUBJL24X,PUBAU24X,PUBSE24X,PUBOC24X,PUBNO24X,PUBDE24X,PEGJA24,PEGFE24,PEGMA24,PEGAP24,PEGMY24,PEGJU24,PEGJL24,PEGAU24,PEGSE24,PEGOC24,PEGNO24,PEGDE24,PDKJA24,PDKFE24,PDKMA24,PDKAP24,PDKMY24,PDKJU24,PDKJL24,PDKAU24,PDKSE24,PDKOC24,PDKNO24,PDKDE24,PNGJA24,PNGFE24,PNGMA24,PNGAP24,PNGMY24,PNGJU24,PNGJL24,PNGAU24,PNGSE24,PNGOC24,PNGNO24,PNGDE24,POGJA24,POGFE24,POGMA24,POGAP24,POGMY24,POGJU24,POGJL24,POGAU24,POGSE24,POGOC24,POGNO24,POGDE24,POEJA24,POEFE24,POEMA24,POEAP24,POEMY24,POEJU24,POEJL24,POEAU24,POESE24,POEOC24,POENO24,POEDE24,PNEJA24,PNEFE24,PNEMA24,PNEAP24,PNEMY24,PNEJU24,PNEJL24,PNEAU24,PNESE24,PNEOC24,PNENO24,PNEDE24,PRXJA24,PRXFE24,PRXMA24,PRXAP24,PRXMY24,PRXJU24,PRXJL24,PRXAU24,PRXSE24,PRXOC24,PRXNO24,PRXDE24,PRIJA24,PRIFE24,PRIMA24,PRIAP24,PRIMY24,PRIJU24,PRIJL24,PRIAU24,PRISE24,PRIOC24,PRINO24,PRIDE24,HPEJA24,HPEFE24,HPEMA24,HPEAP24,HPEMY24,HPEJU24,HPEJL24,HPEAU24,HPESE24,HPEOC24,HPENO24,HPEDE24,HPDJA24,HPDFE24,HPDMA24,HPDAP24,HPDMY24,HPDJU24,HPDJL24,HPDAU24,HPDSE24,HPDOC24,HPDNO24,HPDDE24,HPNJA24,HPNFE24,HPNMA24,HPNAP24,HPNMY24,HPNJU24,HPNJL24,HPNAU24,HPNSE24,HPNOC24,HPNNO24,HPNDE24,HPOJA24,HPOFE24,HPOMA24,HPOAP24,HPOMY24,HPOJU24,HPOJL24,HPOAU24,HPOSE24,HPOOC24,HPONO24,HPODE24,HPXJA24,HPXFE24,HPXMA24,HPXAP24,HPXMY24,HPXJU24,HPXJL24,HPXAU24,HPXSE24,HPXOC24,HPXNO24,HPXDE24,HPRJA24,HPRFE24,HPRMA24,HPRAP24,HPRMY24,HPRJU24,HPRJL24,HPRAU24,HPRSE24,HPROC24,HPRNO24,HPRDE24,INSJA24X,INSFE24X,INSMA24X,INSAP24X,INSMY24X,INSJU24X,INSJL24X,INSAU24X,INSSE24X,INSOC24X,INSNO24X,INSDE24X,PRVEV24,TRIEV24,MCREV24,MCDEV24,VAEV24,GVAEV24,GVBEV24,GVCEV24,UNINS24,INSCOV24,INSURC24,TRICH31X,TRICH42X,TRICH24X,TRI31X,TRI42X,TRI24X,MCRPHD31,MCRPHD42,MCRPHD24,MCRPD31,MCRPD42,MCRPD24,MCRPD31X,MCRPD42X,MCRPD24X,MCRPHO31,MCRPHO42,MCRPHO24,MCDHMO31,MCDHMO42,MCDHMO24,MCDMC31,MCDMC42,MCDMC24,PRVHMO31_M23,PRVHMO42_M23,PRVHMO24_M23,FSAGT31,HASFSA31,PFSAMT31,PREVCOVR,MORECOVR,TRICR31X,TRICR42X,TRICR53X,TRICR24X,TRIAT31X,TRIAT42X,TRIAT53X,TRIAT24X,MCAID31,MCAID42,MCAID53,MCAID24,MCAID31X,MCAID42X,MCAID53X,MCAID24X,MCARE31,MCARE42,MCARE53,MCARE24,MCARE31X,MCARE42X,MCARE53X,MCARE24X,MCDAT31X,MCDAT42X,MCDAT53X,MCDAT24X,GOVTA31,GOVTA42,GOVTA53,GOVTA24,GOVAAT31,GOVAAT42,GOVAAT53,GOVAAT24,GOVTB31,GOVTB42,GOVTB53,GOVTB24,GOVBAT31,GOVBAT42,GOVBAT53,GOVBAT24,GOVTC31,GOVTC42,GOVTC53,GOVTC24,GOVCAT31,GOVCAT42,GOVCAT53,GOVCAT24,VAPROG31,VAPROG42,VAPROG53,VAPROG24,VAPRAT31,VAPRAT42,VAPRAT53,VAPRAT24,IHS31,IHS42,IHS53,IHS24,IHSAT31,IHSAT42,IHSAT53,IHSAT24,PRIDK31,PRIDK42,PRIDK53,PRIDK24,PRIEU31,PRIEU42,PRIEU53,PRIEU24,PRING31,PRING42,PRING53,PRING24,PRIOG31,PRIOG42,PRIOG53,PRIOG24,PRINEO31,PRINEO42,PRINEO53,PRINEO24,PRIEUO31,PRIEUO42,PRIEUO53,PRIEUO24,PRSTX31,PRSTX42,PRSTX53,PRSTX24,PRIV31,PRIV42,PRIV53,PRIV24,PRIVAT31,PRIVAT42,PRIVAT53,PRIVAT24,PUB31X,PUB42X,PUB53X,PUB24X,PUBAT31X,PUBAT42X,PUBAT53X,PUBAT24X,VERFLG31,VERFLG42,VERFLG24,INS31X,INS42X,INS53X,INS24X,INSAT31X,INSAT42X,INSAT53X,INSAT24X,DENTIN31_M23,DENTIN42_M23,DENTIN53_M23,DNTINS31_M23,DNTINS24_M23,PMEDIN31,PMEDIN42,PMEDIN53,PMDINS31,PMDINS24,PROBPY42,CRFMPY42,PYUNBL42,MEDDEBT42,PMEDUP31,PMEDUP42,PMEDUP53,PMEDPY31,PMEDPY42,PMEDPY53,TOTTCH24,TOTEXP24,TOTSLF24,TOTMCR24,TOTMCD24,TOTPRV24,TOTVA24,TOTTRI24,TOTOFD24,TOTSTL24,TOTWCP24,TOTOSR24,TOTPTR24,TOTOTH24,OBTOTV24,OBVTCH24,OBVEXP24,OBVSLF24,OBVMCR24,OBVMCD24,OBVPRV24,OBVVA24,OBVTRI24,OBVOFD24,OBVSTL24,OBVWCP24,OBVOSR24,OBVPTR24,OBVOTH24,OBDRV24,OBDTCH24,OBDEXP24,OBDSLF24,OBDMCR24,OBDMCD24,OBDPRV24,OBDVA24,OBDTRI24,OBDOFD24,OBDSTL24,OBDWCP24,OBDOSR24,OBDPTR24,OBDOTH24,OPTOTV24,OPTTCH24,OPTEXP24,OPTSLF24,OPTMCR24,OPTMCD24,OPTPRV24,OPTVA24,OPTTRI24,OPTOFD24,OPTSTL24,OPTWCP24,OPTOSR24,OPTPTR24,OPTOTH24,OPFTCH24,OPFEXP24,OPFSLF24,OPFMCR24,OPFMCD24,OPFPRV24,OPFVA24,OPFTRI24,OPFOFD24,OPFSTL24,OPFWCP24,OPFOSR24,OPFPTR24,OPFOTH24,OPDEXP24,OPDTCH24,OPDSLF24,OPDMCR24,OPDMCD24,OPDPRV24,OPDVA24,OPDTRI24,OPDOFD24,OPDSTL24,OPDWCP24,OPDOSR24,OPDPTR24,OPDOTH24,OPDRV24,OPVTCH24,OPVEXP24,OPVSLF24,OPVMCR24,OPVMCD24,OPVPRV24,OPVVA24,OPVTRI24,OPVOFD24,OPVSTL24,OPVWCP24,OPVOSR24,OPVPTR24,OPVOTH24,OPSEXP24,OPSTCH24,OPSSLF24,OPSMCR24,OPSMCD24,OPSPRV24,OPSVA24,OPSTRI24,OPSOFD24,OPSSTL24,OPSWCP24,OPSOSR24,OPSPTR24,OPSOTH24,ERTOT24,ERTTCH24,ERTEXP24,ERTSLF24,ERTMCR24,ERTMCD24,ERTPRV24,ERTVA24,ERTTRI24,ERTOFD24,ERTSTL24,ERTWCP24,ERTOSR24,ERTPTR24,ERTOTH24,ERFTCH24,ERFEXP24,ERFSLF24,ERFMCR24,ERFMCD24,ERFPRV24,ERFVA24,ERFTRI24,ERFOFD24,ERFSTL24,ERFWCP24,ERFOSR24,ERFPTR24,ERFOTH24,ERDEXP24,ERDTCH24,ERDSLF24,ERDMCR24,ERDMCD24,ERDPRV24,ERDVA24,ERDTRI24,ERDOFD24,ERDSTL24,ERDWCP24,ERDOSR24,ERDPTR24,ERDOTH24,IPDIS24,IPTEXP24,IPTTCH24,IPTSLF24,IPTMCR24,IPTMCD24,IPTPRV24,IPTVA24,IPTTRI24,IPTOFD24,IPTSTL24,IPTWCP24,IPTOSR24,IPTPTR24,IPTOTH24,IPFEXP24,IPFTCH24,IPFSLF24,IPFMCR24,IPFMCD24,IPFPRV24,IPFVA24,IPFTRI24,IPFOFD24,IPFSTL24,IPFWCP24,IPFOSR24,IPFPTR24,IPFOTH24,IPDEXP24,IPDTCH24,IPDSLF24,IPDMCR24,IPDMCD24,IPDPRV24,IPDVA24,IPDTRI24,IPDOFD24,IPDSTL24,IPDWCP24,IPDOSR24,IPDPTR24,IPDOTH24,IPNGTD24,DVTOT24,DVTTCH24,DVTEXP24,DVTSLF24,DVTMCR24,DVTMCD24,DVTPRV24,DVTVA24,DVTTRI24,DVTOFD24,DVTSTL24,DVTWCP24,DVTOSR24,DVTPTR24,DVTOTH24,HHTOTD24,HHAGD24,HHATCH24,HHAEXP24,HHASLF24,HHAMCR24,HHAMCD24,HHAPRV24,HHAVA24,HHATRI24,HHAOFD24,HHASTL24,HHAWCP24,HHAOSR24,HHAPTR24,HHAOTH24,HHINDD24,HHNTCH24,HHNEXP24,HHNSLF24,HHNMCD24,HHNMCR24,HHNPRV24,HHNVA24,HHNTRI24,HHNOFD24,HHNSTL24,HHNWCP24,HHNOSR24,HHNPTR24,HHNOTH24,HHINFD24,VISEXP24,VISTCH24,VISSLF24,VISMCR24,VISMCD24,VISPRV24,VISVA24,VISTRI24,VISOFD24,VISSTL24,VISWCP24,VISOSR24,VISPTR24,VISOTH24,OTHTCH24,OTHEXP24,OTHSLF24,OTHMCR24,OTHMCD24,OTHPRV24,OTHVA24,OTHTRI24,OTHOFD24,OTHSTL24,OTHWCP24,OTHOSR24,OTHPTR24,OTHOTH24,RXTOT24,RXEXP24,RXSLF24,RXMCR24,RXMCD24,RXPRV24,RXVA24,RXTRI24,RXOFD24,RXSTL24,RXWCP24,RXOSR24,RXPTR24,RXOTH24,PERWT24F_x,FAMWT24F,FAMWT24C,VARSTR_x,VARPSU_x,SAQWT24F,CSAQW24F,ESAQWT24F,PESAQWT24F,DUID_y,PID_y,CONDN,CONDIDX,PANEL_y,CONDRN,AGEDIAG,CRND1,CRND2,CRND3,CRND4,CRND5,INJURY,ACCDNWRK,ICD10CDX,CCSR1X,CCSR2X,CCSR3X,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND,PERWT24F_y,VARSTR_y,VARPSU_y
0,2810003,101,2810003101,28,2024,A,A,A,A,A,A,1,1,A,A,A,A,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,4,4,4,101,101,101,101,1,1,1,1,1,1,1,1,1,1,2,2,8,2023,2,2024,2,2024,11,2024,11,2024,12,2024,12,2024,1,1,1,1,1,1,1,1,1,1,1,11,11,11,60,60,60,66,67,67,67,67,3,1957,2,1,1,3,3,1,2,2,9,2,2,2,2,995,995,995,995,2,2,2,2,12,3,-1,-1,-1,-1,4,4,4,2,1,1,1,1,2,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,2,-1,2,-1,2,-1,1,30,6,2,-1,2,-1,2,1,65,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,1,3,55,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,3,3,3,3,4,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,3,1,1,1,2,2,2,1,1,2,4,3,2,2,2,2,1,1,4,2,4,5,4,3,3,2,2,1,2,0,1,1,7,1,1,2,3,1,1,6,1,1,1,1,2,2,1,4,2,2,1,1,1,2,1,3,-1,-1,-1,1,1,1,1,3,2,1,2,1,3,1,-1,-1,2,1,5,1,-1,2,1,36.70,51.30,0,7,2024,1,18.29,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,3,3,3,-1,-1,-1,-1,-1,-1,-1,2,2,2,2,4,1,1,1,1,4,3,61,520.0,1,0.0,3,12.0,2,52.0,1,1,6,2,2,2,2,2,2,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5,2,-1,-1,-1,-1,-1,-1,-1,-1,1,2,2,2025,1,1,2,-1,1,3,2,-1,1,3,1,3,1,4,1,-1,2,2,1,2,2,2,1,3,4,2,2,-1,-1,-1,14.00,-1.0,-1.0,0,0,0,3,-1,-1,1,-1,-1,3,-1,-1,15.25,-1.00,-1.00,16,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,1,-1,-1,-8,-1,-1,5,-1,-1,100,-1,-1,1,-1,-1,2,-1,-1,-1,-1,6,3,-1,7,-1,2,2023,-1,-1,-1,-1,1,8,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,-1,-1,-1,1,-1,-1,2,-1,-1,-15,-1,-1,-15,-1,-1,-1,-1,-1,1,34,34,2,-1,-1,100,-1,-1,1,-1,-1,5,-1,-1,8,-1,-1,16,-1,-1,1,-1,-1,2,-1,-1,-1,-1,-1,15.25,-1.00,-1.00,2,-1,-1,1,-1,-1,1,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,1,1,1,-1,-1,1,2,-1,-1,82732,82732,5,549.90,3416,4,0,1,0,1,0,1,50716,6,2000,1,175529,1,5000,1,21600,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,2810003A1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,2,2,2,2,2,2,2,4,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,2,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,95,95,95,1,1,1,1,1,1,1,1,1,1,2,1,2,2,2,2,2,2,2,1,-1,1,1,1,1,1,1,1,56703,12912,2751,10161,0,0,0,0,0,0,0,0,0,0,14,5501,2347,618,1729,0,0,0,0,0,0,0,0,0,0,6,3851,1646,355,1291,0,0,0,0,0,0,0,0,0,0,1,5005,507,150,357,0,0,0,0,0,0,0,0,0,0,2000,428,150,278,0,0,0,0,0,0,0,0,0,0,79,3005,0,79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,36000,6245,1475,4770,0,0,0,0,0,0,0,0,0,0,36000,6245,1475,4770,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,899,5581,0,899,0,0,0,0,0,0,0,0,0,0,177,1554,0,177,0,0,0,0,0,0,0,0,0,0,722,4027,0,722,0,0,0,0,0,0,0,0,0,0,1,5,2380,973,0,973,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,210,210,210,0,0,0,0,0,0,0,0,0,0,0,2026,1533,275,1258,0,0,0,0,0,0,0,0,0,0,17,198,23,175,0,0,0,0,0,0,0,0,0,0,16532.179400,14481.89179,14481.89179,2062,1,19220.25904,0.0,19419.845140,22951.575300,2810003,101,16,2810003101016,28,3,-1,-1,-1,1,1,1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,1,2,1,16532.179400,2062,1

In [42]:
# attributes of the newly joined dataframe
joined.columns

Index(['DUID_x', 'PID_x', 'DUPERSID', 'PANEL_x', 'DATAYEAR', 'FAMID31',
       'FAMID42', 'FAMID53', 'FAMID24', 'FAMIDYR',
       ...
       'CCSR4X', 'HHCOND', 'IPCOND', 'OPCOND', 'OBCOND', 'ERCOND', 'RXCOND',
       'PERWT24F_y', 'VARSTR_y', 'VARPSU_y'],
      dtype='str', length=1643)

### Data Preprocessing

In [43]:
for column in joined.columns:
    if "_x" in column:
        # change attributes that have trailing '_x' 
        joined.rename(columns={column: column.replace("_x", "")}, inplace=True)
    elif "_y" in column:
        # drop unnecessary columns '_y'
        joined = joined.drop([column], axis = 1)

In [46]:
# confirm attributes with _x renamed
# and attributes with _y removed
joined.columns

Index(['DUID', 'PID', 'DUPERSID', 'PANEL', 'DATAYEAR', 'FAMID31', 'FAMID42',
       'FAMID53', 'FAMID24', 'FAMIDYR',
       ...
       'CCSR1X', 'CCSR2X', 'CCSR3X', 'CCSR4X', 'HHCOND', 'IPCOND', 'OPCOND',
       'OBCOND', 'ERCOND', 'RXCOND'],
      dtype='str', length=1637)

In [47]:
joined

,DUID,PID,DUPERSID,PANEL,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID24,FAMIDYR,CPSFAMID,FCSZ1231,FCRP1231,RULETR31,RULETR42,RULETR53,RULETR24,RUSIZE31,RUSIZE42,RUSIZE53,RUSIZE24,RUCLAS31,RUCLAS42,RUCLAS53,RUCLAS24,FAMSZE31,FAMSZE42,FAMSZE53,FAMSZE24,FMRS1231,FAMS1231,FAMSZEYR,FAMRFPYR,REGION31,REGION42,REGION53,REGION24,REFPRS31,REFPRS42,REFPRS53,REFPRS24,RESP31,RESP42,RESP53,RESP24,PROXY31,PROXY42,PROXY53,PROXY24,INTVLANG,INTVTYPE31,INTVTYPE42,INTVTYPE53,BEGRFM31,BEGRFY31,ENDRFM31,ENDRFY31,BEGRFM42,BEGRFY42,ENDRFM42,ENDRFY42,BEGRFM53,BEGRFY53,ENDRFM53,ENDRFY53,ENDRFM24,ENDRFY24,KEYNESS,INSCOP31,INSCOP42,INSCOP53,INSCOP24,INSC1231,INSCOPE,ELGRND31,ELGRND42,ELGRND53,ELGRND24,PSTATS31,PSTATS42,PSTATS53,RURSLT31,RURSLT42,RURSLT53,AGE31X,AGE42X,AGE53X,AGE24X,AGELAST,DOBMM,DOBYY,SEX,RACEV1X,RACEV2X,RACEAX,RACEBX,RACEWX,RACETHX,HISPANX,HISPNCAT,MARRY31X,MARRY42X,MARRY53X,MARRY24X,SPOUID31,SPOUID42,SPOUID53,SPOUID24,SPOUIN31,SPOUIN42,SPOUIN53,SPOUIN24,EDUCYR,HIDEG,FTSTU31X,FTSTU42X,FTSTU53X,FTSTU24X,ACTDTY31,ACTDTY42,ACTDTY53,EVERSERVED,REFRL31X,REFRL42X,REFRL53X,REFRL24X,OTHLGSPK,WHTLGSPK,HWELLSPK,BORNUSA,YRSINUS,MOPID31X,MOPID42X,MOPID53X,DAPID31X,DAPID42X,DAPID53X,HIBPDX,HIBPAGED,BPMLDX,CHDDX,CHDAGED,ANGIDX,ANGIAGED,MIDX,MIAGED,OHRTDX,OHRTAGED,OHRTTYPE,STRKDX,STRKAGED,EMPHDX,EMPHAGED,CHBRON31,CHOLDX,CHOLAGED,CANCERDX,CABLADDR,CABREAST,CACERVIX,CACOLON,CALUNG,CALYMPH,CAMELANO,CAOTHER,CAPROSTA,CASKINNM,CASKINDK,CAUTERUS,DIABDX_M18,DIABAGED,JTPAIN31_M18,ARTHDX,ARTHTYPE,ARTHAGED,ASTHDX,ASTHAGED,ASSTIL31,ASATAK31,ASTHEP31,ASACUT31,ASMRCN31,ASPREV31,ASDALY31,ASPKFL31,ASEVFL31,ASWNFL31,ADHDADDX,ADHDAGED,COVIDEVER31,COVIDEVER53,LCEVER31,LCEVER53,COVSYMNOW31,COVSYMNOW53,COVREDABIL31,COVREDABIL53,COVID12MO31,COVID12MO53,COVMNTHX31,COVMNTHX53,COVYRDX31,COVYRDX53,RTHLTH31,RTHLTH42,RTHLTH53,MNHLTH31,MNHLTH42,MNHLTH53,IADLHP31,ADLHLP31,AIDHLP31,WLKLIM31,LFTDIF31,STPDIF31,WLKDIF31,MILDIF31,STNDIF31,BENDIF31,RCHDIF31,FNGRDF31,ACTLIM31,WRKLIM31,HSELIM31,SCHLIM31,UNABLE31,SOCLIM31,COGLIM31,DFHEAR42,DFSEE42,DFCOG42,DFWLKC42,DFDRSB42,DFERND42,ANYLMI24,CHPMED42,CHPMHB42,CHPMCN42,CHSERV42,CHSRHB42,CHSRCN42,CHLIMI42,CHLIHB42,CHLICO42,CHTHER42,CHTHHB42,CHTHCO42,CHCOUN42,CHEMPB42,CSHCN42,MESHGT42,WHNHGT42,MESWGT42,WHNWGT42,CHBMIX42,MESVIS42,EATHLT42,WHNEAT42,PHYSCL42,WHNPHY42,SAFEST42,WHNSAF42,BOOST42,WHNBST42,LAPBLT42,WHNLAP42,HELMET42,WHNHEL42,NOSMOK42,WHNSMK42,TIMALN42,LSTETH53,PHYEXE53,OFTSMK53,COVAXEVR31,COVAXEVR42,COVAXEVR53,COVAXNEW31,COVAXNEW42,COVAXNEW53,SAQELIG,ADPROX42,ADSEX42,ADAGE42_M24,ADGENH42,ADDAYA42,ADCLIM42,ADACLS42,ADWKLM42,ADEMLS42,ADMWCF42,ADPAIN42,ADPCFL42,ADENGY42,ADPRST42,ADSOCA42,ADCOMPAN42,ADLEFTOUT42,ADISOL42,ADNERV42,ADHOPE42,ADREST42,ADSAD42,ADEFRT42,ADWRTH42,K6SUM42,ADINTR42,ADDPRS42,PHQ242,ADSLEEP42,ADDAYEXER42,ADMINSEXER42,ADASKALC42,ADNUMDRK42,ADRNK542_M24,ADRNK442_M24,ADOFTALC42,ADSTAL42,ADMNTRT42,ADUNABTRT42,ADPROBTRT42,ADTRTEXP42,ADBRTC42,ADMDVT42,ADFLST42,ADWGHD42,ADWTAD42,ADTBAC42,ADOFTB42,ADQTTB42,ADQTMD42,ADQTHP42,ADMOOD42,ADBPCK42,ADCHLC42,ADPNEU42_M24,ADSHNG42_M24,ADNOAP42_M24,ADDSCU42_M24,ADCOLN42_M24,ADCLNS42_M24,ADSGMD42_M24,ADBLDS42_M24,ADPROS42_M24,ADPSAG42_M24,ADUTRM42,ADPAP42,ADPAPG42,ADOSTP42_M24,ADBNDN42_M24,ADBRST42_M24,ADMMGR42_M24,VPCS42,VMCS42,VRFLAG42,ADCMPM42,ADCMPY42,ADLANG42,ADBMI42,CSAQELIG,CSLANG42,CCNRDI42,CDIAG42,CTRTMT42,CLSTRT42,CBCK42,CBCKYR42,CFTRT42,CWRKP42,CEXTM42,CWRKLV42,CNPTLD42,CWRKQT42,CNGFLX42,CPROM42,CERET42,CDLRET42,CWKLIM42,CEWRDT42,CESHTD42,CETIME42,CEBRKS42,CEDUTY42,CESKLL42,CERHAB42,CEWRHM42,CEOTHR42,CENOND42,CENONE42,CENAPP42,CDNHLP42,CJWAGE42,CJFIRE42,CJPROM42,CJDUTY42,CJNONE42,CLPROD42,CFRET42,CLHINS42,CSLHIN42_M24,CNCMED42,CNCTRP42,CNCLOD42,CNCCHD42,CNCHME42,CNCNON42,CNCNTS42,CFNDBT42,CFNAMT42,CFNVAC42,CFNPUR42,CFNSPD42,CFNSAV42,CFNLIV42,CFNOTH42,CFNONE42,CFNUNB42,CFNPMT42,CFNSTB42,CFNINC42,CDLPRS42,CDLVST42,CDLTRT42,CDLFUP42,CDLMNT42,CDLOTH42,CDLNONE42,CMCPSY42,CMCTRL42,CMCOST42,CMCWRK42,CMCFUP42,CMCEFF42,CMCSTY42,CMCTRT42,CCOGIM42,CCNEUR42,CCFATG42,CCNAUS42,CCPAIN42,CCMOTH42,CCOTHR42,CANRDX42,CFCARE42,CFRCUR42,CFTREMT42,CFOTHH42,CFTRSE42,CFPHYS42,CFSCRN42,CFREFR42,CFOTHR42,CPLSTN42,CPEXPL42,CPRESP42,CPTIME42,CPSPCP42,CPSONC42,CPSRAD42,CPSURG42,CPSOBG42,CPSDEN42,CPSOTH42,CPSDKN42,CPSYCH42,CNCAND42,CNCPND42,CNCOST42,CNCINS42,CNCACS42,CNCANX42,CNCTSP42,CNCDKN42,CNCOTH42,CEFACT42,CEFLCT42,CEFOG42,CEFMTL42,CEFUND42,CEFBCK42,CEFSTG42,CEFCOP42,CEFPOS42,CEFHLT42,CEFPHL42,CEFPAC42,CEFPIN42,CEFFTG42,CEFQLF42,CEFMHL42,CEFRLT42,CEFMPR42,CFDSKP42,CFDLST42,CFDBAL42,CWRRET42,CWRBIL42,CWRHOU42,CHPBED42,CHPDOC42,CHPCHO42,CHPERR42,CSAQPROXY42,CSCMPM42,CSCMPY42,DDNWRK24_M24,OTHNDD24_M24,FSOUT42,FSLAST42,FSAFRD42,FSSKIP42,FSSKDY42,FSLESS42,FSHGRY42,FSWTLS42,FSNEAT42,FSNEDY42,FWRENT42,FWUTIL42,FWCRED42,FWDEBT42,FWUNEXP42,ESAQELIG,EQMOBI53,EQSELF53,EQACTI53,EQPAIN53,EQDEPR53,EQVAS53,EQMVAM53,EQMVPER53,EQOVAM53,EQOVPER53,EQMBAM53,EQMBPER53,EQPPAM53,EQPPPER53,EQDENY53,EQPAYB53,EQSLEI53,EQSBIG53,EQSBAS53,EQSSAV53,EQSLIV53,EQSOTH53,EQSNON53,EQWRKP53,EQENOND53,EQEHLPWR53,EQESHRT53,EQETIME53,EQEBRKS53,EQEDUTY53,EQESKLL53,EQERHAB53,EQEWFH53,EQEOTHR53,EQENOHLP53,EQESLFEMP53,EQFRHP53,EQWINS53,EQWSIK53,EQLWLD53,EQLSAV53,EQLDEN53,EQLUPD53,EQLENH53,EQLJBSC53,EQLSIN53,EQLVOT53,EQEMP753,EQPROD53,EQACTV53,EQCARE53,EQCRRL53,EQCRLV53,EQCRLG53,EQPERS53,EQTASK53,EQALON53,EQCRNW53,EQTIME53,ESAQPROXY53,ESAQMODE53,EQCMPM53,EQCMPY53,ACCELI42,HAVEUS42,PRACTP42,YNOUSC42_M18,PROVTY42_M18,PLCTYP42,TMTKUS42,TYPEPE42,LOCATN42,PHNREG42,OFFHOU42,AFTHOU42,TREATM42,DECIDE42,EXPLOP42,PRVSPK42,DLAYCA42,AFRDCA42,DLAYDN42,AFRDDN42,DLAYPM42,AFRDPM42,EMPST31,EMPST42,EMPST53,RNDFLG31,MORJOB31,MORJOB42,MORJOB53,EVRWRK,HRWG31X,HRWG42X,HRWG53X,HRWGIM31,HRWGIM42,HRWGIM53,HRHOW31,HRHOW42,HRHOW53,DIFFWG31,DIFFWG42,DIFFWG53,NHRWGRND31,NHRWGRND42,NHRWGRND53,NHRWG31_M23,NHRWG42_M23,NHRWG53_M23,HOUR31,HOUR42,HOUR53,TEMPJB31,TEMPJB42,TEMPJB53,SSNLJB31,SSNLJB42,SSNLJB53,SELFCM31,SELFCM42,SELFCM53,DISVW31X,DISVW42X,DISVW53X,CHOIC31,CHOIC42,CHOIC53,INDCAT31_17,INDCAT42_17,INDCAT53_17,NUMEMP31,NUMEMP42,NUMEMP53,MORE31,MORE42,MORE53,UNION31,UNION42,UNION53,NWK31,NWK42,NWK53,CHGJ3142,CHGJ4253,YCHJ3142,YCHJ4253,STJBMM31,STJBYY31,STJBMM42,STJBYY42,STJBMM53,STJBYY53,EVRETIRE,OCCCAT31_18,OCCCAT42_18,OCCCAT53_18,PAYVAC31,PAYVAC42,PAYVAC53,SICPAY31,SICPAY42,SICPAY53,PAYDR31,PAYDR42,PAYDR53,RETPLN31,RETPLN42,RETPLN53,BSNTY31,BSNTY42,BSNTY53,JOBORG31,JOBORG42,JOBORG53,HELD31X,HELD42X,HELD53X,OFFER31X,OFFER42X,OFFER53X,OFREMP31,OFREMP42,OFREMP53,OUTFLAG31,OUTFLAG42,OUTFLAG53,EMPST31H,EMPST42H,EMPST53H,SLFCM31H,SLFCM42H,SLFCM53H,NMEMP31H,NMEMP42H,NMEMP53H,MORE31H,MORE42H,MORE53H,INDCT31H_17,INDCT42H_17,INDCT53H_17,OCCCT31H_18,OCCCT42H_18,OCCCT53H_18,HOUR31H,HOUR42H,HOUR53H,JBORG31H,JBORG42H,JBORG53H,UNION31H,UNION42H,UNION53H,BSNTY31H,BSNTY42H,BSNTY53H,HRWG31H,HRWG42H,HRWG53H,CMJHLD31,CMJHLD42,CMJHLD53,OFFER31H,OFFER42H,OFFER53H,OFEMP31H,OFEMP42H,OFEMP53H,PYVAC31H,PYVAC42H,PYVAC53H,SCPAY31H,SCPAY42H,SCPAY53H,PAYDR31H,PAYDR42H,PAYDR53H,RTPLN31H,RTPLN42H,RTPLN53H,FILEDR24,WILFIL24,FLSTAT24,FILER24,JTINRU24,JNTPID24,TAXFRM24,FOODST24,FOODMN24,FOODVL24,TTLP24X,FAMINC24,POVCAT24,POVLEV24,WAGEP24X,WAGIMP24,BUSNP24X,BUSIMP24,UNEMP24X,UNEIMP24,WCMPP24X,WCPIMP24,INTRP24X,INTIMP24,DIVDP24X,DIVIMP24,SALEP24X,SALIMP24,PENSP24X,PENIMP24,SSECP24X,SSCIMP24,TRSTP24X,TRTIMP24,VETSP24X,VETIMP24,IRASP24X,IRAIMP24,ALIMP24X,ALIIMP24,CHLDP24X,CHLIMP24,CASHP24X,CSHIMP24,SSIP24X,SSIIMP24,PUBP24X,PUBIMP24,OTHRP24X,OTHIMP24,HIEUIDX,TRIJA24X,TRIFE24X,TRIMA24X,TRIAP24X,TRIMY24X,TRIJU24X,TRIJL24X,TRIAU24X,TRISE24X,TRIOC24X,TRINO24X,TRIDE24X,MCRJA24,MCRFE24,MCRMA24,MCRAP24,MCRMY24,MCRJU24,MCRJL24,MCRAU24,MCRSE24,MCROC24,MCRNO24,MCRDE24,MCRJA24X,MCRFE24X,MCRMA24X,MCRAP24X,MCRMY24X,MCRJU24X,MCRJL24X,MCRAU24X,MCRSE24X,MCROC24X,MCRNO24X,MCRDE24X,MCDJA24,MCDFE24,MCDMA24,MCDAP24,MCDMY24,MCDJU24,MCDJL24,MCDAU24,MCDSE24,MCDOC24,MCDNO24,MCDDE24,MCDJA24X,MCDFE24X,MCDMA24X,MCDAP24X,MCDMY24X,MCDJU24X,MCDJL24X,MCDAU24X,MCDSE24X,MCDOC24X,MCDNO24X,MCDDE24X,GVAJA24,GVAFE24,GVAMA24,GVAAP24,GVAMY24,GVAJU24,GVAJL24,GVAAU24,GVASE24,GVAOC24,GVANO24,GVADE24,GVBJA24,GVBFE24,GVBMA24,GVBAP24,GVBMY24,GVBJU24,GVBJL24,GVBAU24,GVBSE24,GVBOC24,GVBNO24,GVBDE24,GVCJA24,GVCFE24,GVCMA24,GVCAP24,GVCMY24,GVCJU24,GVCJL24,GVCAU24,GVCSE24,GVCOC24,GVCNO24,GVCDE24,VAPJA24,VAPFE24,VAPMA24,VAPAP24,VAPMY24,VAPJU24,VAPJL24,VAPAU24,VAPSE24,VAPOC24,VAPNO24,VAPDE24,IHSJA24,IHSFE24,IHSMA24,IHSAP24,IHSMY24,IHSJU24,IHSJL24,IHSAU24,IHSSE24,IHSOC24,IHSNO24,IHSDE24,PUBJA24X,PUBFE24X,PUBMA24X,PUBAP24X,PUBMY24X,PUBJU24X,PUBJL24X,PUBAU24X,PUBSE24X,PUBOC24X,PUBNO24X,PUBDE24X,PEGJA24,PEGFE24,PEGMA24,PEGAP24,PEGMY24,PEGJU24,PEGJL24,PEGAU24,PEGSE24,PEGOC24,PEGNO24,PEGDE24,PDKJA24,PDKFE24,PDKMA24,PDKAP24,PDKMY24,PDKJU24,PDKJL24,PDKAU24,PDKSE24,PDKOC24,PDKNO24,PDKDE24,PNGJA24,PNGFE24,PNGMA24,PNGAP24,PNGMY24,PNGJU24,PNGJL24,PNGAU24,PNGSE24,PNGOC24,PNGNO24,PNGDE24,POGJA24,POGFE24,POGMA24,POGAP24,POGMY24,POGJU24,POGJL24,POGAU24,POGSE24,POGOC24,POGNO24,POGDE24,POEJA24,POEFE24,POEMA24,POEAP24,POEMY24,POEJU24,POEJL24,POEAU24,POESE24,POEOC24,POENO24,POEDE24,PNEJA24,PNEFE24,PNEMA24,PNEAP24,PNEMY24,PNEJU24,PNEJL24,PNEAU24,PNESE24,PNEOC24,PNENO24,PNEDE24,PRXJA24,PRXFE24,PRXMA24,PRXAP24,PRXMY24,PRXJU24,PRXJL24,PRXAU24,PRXSE24,PRXOC24,PRXNO24,PRXDE24,PRIJA24,PRIFE24,PRIMA24,PRIAP24,PRIMY24,PRIJU24,PRIJL24,PRIAU24,PRISE24,PRIOC24,PRINO24,PRIDE24,HPEJA24,HPEFE24,HPEMA24,HPEAP24,HPEMY24,HPEJU24,HPEJL24,HPEAU24,HPESE24,HPEOC24,HPENO24,HPEDE24,HPDJA24,HPDFE24,HPDMA24,HPDAP24,HPDMY24,HPDJU24,HPDJL24,HPDAU24,HPDSE24,HPDOC24,HPDNO24,HPDDE24,HPNJA24,HPNFE24,HPNMA24,HPNAP24,HPNMY24,HPNJU24,HPNJL24,HPNAU24,HPNSE24,HPNOC24,HPNNO24,HPNDE24,HPOJA24,HPOFE24,HPOMA24,HPOAP24,HPOMY24,HPOJU24,HPOJL24,HPOAU24,HPOSE24,HPOOC24,HPONO24,HPODE24,HPXJA24,HPXFE24,HPXMA24,HPXAP24,HPXMY24,HPXJU24,HPXJL24,HPXAU24,HPXSE24,HPXOC24,HPXNO24,HPXDE24,HPRJA24,HPRFE24,HPRMA24,HPRAP24,HPRMY24,HPRJU24,HPRJL24,HPRAU24,HPRSE24,HPROC24,HPRNO24,HPRDE24,INSJA24X,INSFE24X,INSMA24X,INSAP24X,INSMY24X,INSJU24X,INSJL24X,INSAU24X,INSSE24X,INSOC24X,INSNO24X,INSDE24X,PRVEV24,TRIEV24,MCREV24,MCDEV24,VAEV24,GVAEV24,GVBEV24,GVCEV24,UNINS24,INSCOV24,INSURC24,TRICH31X,TRICH42X,TRICH24X,TRI31X,TRI42X,TRI24X,MCRPHD31,MCRPHD42,MCRPHD24,MCRPD31,MCRPD42,MCRPD24,MCRPD31X,MCRPD42X,MCRPD24X,MCRPHO31,MCRPHO42,MCRPHO24,MCDHMO31,MCDHMO42,MCDHMO24,MCDMC31,MCDMC42,MCDMC24,PRVHMO31_M23,PRVHMO42_M23,PRVHMO24_M23,FSAGT31,HASFSA31,PFSAMT31,PREVCOVR,MORECOVR,TRICR31X,TRICR42X,TRICR53X,TRICR24X,TRIAT31X,TRIAT42X,TRIAT53X,TRIAT24X,MCAID31,MCAID42,MCAID53,MCAID24,MCAID31X,MCAID42X,MCAID53X,MCAID24X,MCARE31,MCARE42,MCARE53,MCARE24,MCARE31X,MCARE42X,MCARE53X,MCARE24X,MCDAT31X,MCDAT42X,MCDAT53X,MCDAT24X,GOVTA31,GOVTA42,GOVTA53,GOVTA24,GOVAAT31,GOVAAT42,GOVAAT53,GOVAAT24,GOVTB31,GOVTB42,GOVTB53,GOVTB24,GOVBAT31,GOVBAT42,GOVBAT53,GOVBAT24,GOVTC31,GOVTC42,GOVTC53,GOVTC24,GOVCAT31,GOVCAT42,GOVCAT53,GOVCAT24,VAPROG31,VAPROG42,VAPROG53,VAPROG24,VAPRAT31,VAPRAT42,VAPRAT53,VAPRAT24,IHS31,IHS42,IHS53,IHS24,IHSAT31,IHSAT42,IHSAT53,IHSAT24,PRIDK31,PRIDK42,PRIDK53,PRIDK24,PRIEU31,PRIEU42,PRIEU53,PRIEU24,PRING31,PRING42,PRING53,PRING24,PRIOG31,PRIOG42,PRIOG53,PRIOG24,PRINEO31,PRINEO42,PRINEO53,PRINEO24,PRIEUO31,PRIEUO42,PRIEUO53,PRIEUO24,PRSTX31,PRSTX42,PRSTX53,PRSTX24,PRIV31,PRIV42,PRIV53,PRIV24,PRIVAT31,PRIVAT42,PRIVAT53,PRIVAT24,PUB31X,PUB42X,PUB53X,PUB24X,PUBAT31X,PUBAT42X,PUBAT53X,PUBAT24X,VERFLG31,VERFLG42,VERFLG24,INS31X,INS42X,INS53X,INS24X,INSAT31X,INSAT42X,INSAT53X,INSAT24X,DENTIN31_M23,DENTIN42_M23,DENTIN53_M23,DNTINS31_M23,DNTINS24_M23,PMEDIN31,PMEDIN42,PMEDIN53,PMDINS31,PMDINS24,PROBPY42,CRFMPY42,PYUNBL42,MEDDEBT42,PMEDUP31,PMEDUP42,PMEDUP53,PMEDPY31,PMEDPY42,PMEDPY53,TOTTCH24,TOTEXP24,TOTSLF24,TOTMCR24,TOTMCD24,TOTPRV24,TOTVA24,TOTTRI24,TOTOFD24,TOTSTL24,TOTWCP24,TOTOSR24,TOTPTR24,TOTOTH24,OBTOTV24,OBVTCH24,OBVEXP24,OBVSLF24,OBVMCR24,OBVMCD24,OBVPRV24,OBVVA24,OBVTRI24,OBVOFD24,OBVSTL24,OBVWCP24,OBVOSR24,OBVPTR24,OBVOTH24,OBDRV24,OBDTCH24,OBDEXP24,OBDSLF24,OBDMCR24,OBDMCD24,OBDPRV24,OBDVA24,OBDTRI24,OBDOFD24,OBDSTL24,OBDWCP24,OBDOSR24,OBDPTR24,OBDOTH24,OPTOTV24,OPTTCH24,OPTEXP24,OPTSLF24,OPTMCR24,OPTMCD24,OPTPRV24,OPTVA24,OPTTRI24,OPTOFD24,OPTSTL24,OPTWCP24,OPTOSR24,OPTPTR24,OPTOTH24,OPFTCH24,OPFEXP24,OPFSLF24,OPFMCR24,OPFMCD24,OPFPRV24,OPFVA24,OPFTRI24,OPFOFD24,OPFSTL24,OPFWCP24,OPFOSR24,OPFPTR24,OPFOTH24,OPDEXP24,OPDTCH24,OPDSLF24,OPDMCR24,OPDMCD24,OPDPRV24,OPDVA24,OPDTRI24,OPDOFD24,OPDSTL24,OPDWCP24,OPDOSR24,OPDPTR24,OPDOTH24,OPDRV24,OPVTCH24,OPVEXP24,OPVSLF24,OPVMCR24,OPVMCD24,OPVPRV24,OPVVA24,OPVTRI24,OPVOFD24,OPVSTL24,OPVWCP24,OPVOSR24,OPVPTR24,OPVOTH24,OPSEXP24,OPSTCH24,OPSSLF24,OPSMCR24,OPSMCD24,OPSPRV24,OPSVA24,OPSTRI24,OPSOFD24,OPSSTL24,OPSWCP24,OPSOSR24,OPSPTR24,OPSOTH24,ERTOT24,ERTTCH24,ERTEXP24,ERTSLF24,ERTMCR24,ERTMCD24,ERTPRV24,ERTVA24,ERTTRI24,ERTOFD24,ERTSTL24,ERTWCP24,ERTOSR24,ERTPTR24,ERTOTH24,ERFTCH24,ERFEXP24,ERFSLF24,ERFMCR24,ERFMCD24,ERFPRV24,ERFVA24,ERFTRI24,ERFOFD24,ERFSTL24,ERFWCP24,ERFOSR24,ERFPTR24,ERFOTH24,ERDEXP24,ERDTCH24,ERDSLF24,ERDMCR24,ERDMCD24,ERDPRV24,ERDVA24,ERDTRI24,ERDOFD24,ERDSTL24,ERDWCP24,ERDOSR24,ERDPTR24,ERDOTH24,IPDIS24,IPTEXP24,IPTTCH24,IPTSLF24,IPTMCR24,IPTMCD24,IPTPRV24,IPTVA24,IPTTRI24,IPTOFD24,IPTSTL24,IPTWCP24,IPTOSR24,IPTPTR24,IPTOTH24,IPFEXP24,IPFTCH24,IPFSLF24,IPFMCR24,IPFMCD24,IPFPRV24,IPFVA24,IPFTRI24,IPFOFD24,IPFSTL24,IPFWCP24,IPFOSR24,IPFPTR24,IPFOTH24,IPDEXP24,IPDTCH24,IPDSLF24,IPDMCR24,IPDMCD24,IPDPRV24,IPDVA24,IPDTRI24,IPDOFD24,IPDSTL24,IPDWCP24,IPDOSR24,IPDPTR24,IPDOTH24,IPNGTD24,DVTOT24,DVTTCH24,DVTEXP24,DVTSLF24,DVTMCR24,DVTMCD24,DVTPRV24,DVTVA24,DVTTRI24,DVTOFD24,DVTSTL24,DVTWCP24,DVTOSR24,DVTPTR24,DVTOTH24,HHTOTD24,HHAGD24,HHATCH24,HHAEXP24,HHASLF24,HHAMCR24,HHAMCD24,HHAPRV24,HHAVA24,HHATRI24,HHAOFD24,HHASTL24,HHAWCP24,HHAOSR24,HHAPTR24,HHAOTH24,HHINDD24,HHNTCH24,HHNEXP24,HHNSLF24,HHNMCD24,HHNMCR24,HHNPRV24,HHNVA24,HHNTRI24,HHNOFD24,HHNSTL24,HHNWCP24,HHNOSR24,HHNPTR24,HHNOTH24,HHINFD24,VISEXP24,VISTCH24,VISSLF24,VISMCR24,VISMCD24,VISPRV24,VISVA24,VISTRI24,VISOFD24,VISSTL24,VISWCP24,VISOSR24,VISPTR24,VISOTH24,OTHTCH24,OTHEXP24,OTHSLF24,OTHMCR24,OTHMCD24,OTHPRV24,OTHVA24,OTHTRI24,OTHOFD24,OTHSTL24,OTHWCP24,OTHOSR24,OTHPTR24,OTHOTH24,RXTOT24,RXEXP24,RXSLF24,RXMCR24,RXMCD24,RXPRV24,RXVA24,RXTRI24,RXOFD24,RXSTL24,RXWCP24,RXOSR24,RXPTR24,RXOTH24,PERWT24F,FAMWT24F,FAMWT24C,VARSTR,VARPSU,SAQWT24F,CSAQW24F,ESAQWT24F,PESAQWT24F,CONDN,CONDIDX,CONDRN,AGEDIAG,CRND1,CRND2,CRND3,CRND4,CRND5,INJURY,ACCDNWRK,ICD10CDX,CCSR1X,CCSR2X,CCSR3X,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND
0,2810003,101,2810003101,28,2024,A,A,A,A,A,A,1,1,A,A,A,A,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,4,4,4,101,101,101,101,1,1,1,1,1,1,1,1,1,1,2,2,8,2023,2,2024,2,2024,11,2024,11,2024,12,2024,12,2024,1,1,1,1,1,1,1,1,1,1,1,11,11,11,60,60,60,66,67,67,67,67,3,1957,2,1,1,3,3,1,2,2,9,2,2,2,2,995,995,995,995,2,2,2,2,12,3,-1,-1,-1,-1,4,4,4,2,1,1,1,1,2,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,2,-1,2,-1,2,-1,1,30,6,2,-1,2,-1,2,1,65,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,1,3,55,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,3,3,3,3,4,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,2,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,3,1,1,1,2,2,2,1,1,2,4,3,2,2,2,2,1,1,4,2,4,5,4,3,3,2,2,1,2,0,1,1,7,1,1,2,3,1,1,6,1,1,1,1,2,2,1,4,2,2,1,1,1,2,1,3,-1,-1,-1,1,1,1,1,3,2,1,2,1,3,1,-1,-1,2,1,5,1,-1,2,1,36.70,51.30,0,7,2024,1,18.29,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,3,3,3,-1,-1,-1,-1,-1,-1,-1,2,2,2,2,4,1,1,1,1,4,3,61,520.0,1,0.0,3,12.0,2,52.0,1,1,6,2,2,2,2,2,2,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5,2,-1,-1,-1,-1,-1,-1,-1,-1,1,2,2,2025,1,1,2,-1,1,3,2,-1,1,3,1,3,1,4,1,-1,2,2,1,2,2,2,1,3,4,2,2,-1,-1,-1,14.00,-1.0,-1.0,0,0,0,3,-1,-1,1,-1,-1,3,-1,-1,15.25,-1.00,-1.00,16,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,1,-1,-1,-8,-1,-1,5,-1,-1,100,-1,-1,1,-1,-1,2,-1,-1,-1,-1,6,3,-1,7,-1,2,2023,-1,-1,-1,-1,1,8,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,-1,-1,-1,1,-1,-1,2,-1,-1,-15,-1,-1,-15,-1,-1,-1,-1,-1,1,34,34,2,-1,-1,100,-1,-1,1,-1,-1,5,-1,-1,8,-1,-1,16,-1,-1,1,-1,-1,2,-1,-1,-1,-1,-1,15.25,-1.00,-1.00,2,-1,-1,1,-1,-1,1,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,-1,-1,2,1,1,1,-1,-1,1,2,-1,-1,82732,82732,5,549.90,3416,4,0,1,0,1,0,1,50716,6,2000,1,175529,1,5000,1,21600,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,2810003A1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,2,2,2,2,2,2,2,4,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,2,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,95,95,95,1,1,1,1,1,1,1,1,1,1,2,1,2,2,2,2,2,2,2,1,-1,1,1,1,1,1,1,1,56703,12912,2751,10161,0,0,0,0,0,0,0,0,0,0,14,5501,2347,618,1729,0,0,0,0,0,0,0,0,0,0,6,3851,1646,355,1291,0,0,0,0,0,0,0,0,0,0,1,5005,507,150,357,0,0,0,0,0,0,0,0,0,0,2000,428,150,278,0,0,0,0,0,0,0,0,0,0,79,3005,0,79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,36000,6245,1475,4770,0,0,0,0,0,0,0,0,0,0,36000,6245,1475,4770,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,899,5581,0,899,0,0,0,0,0,0,0,0,0,0,177,1554,0,177,0,0,0,0,0,0,0,0,0,0,722,4027,0,722,0,0,0,0,0,0,0,0,0,0,1,5,2380,973,0,973,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,210,210,210,0,0,0,0,0,0,0,0,0,0,0,2026,1533,275,1258,0,0,0,0,0,0,0,0,0,0,17,198,23,175,0,0,0,0,0,0,0,0,0,0,16532.179400,14481.89179,14481.89179,2062,1,19220.25904,0.0,19419.845140,22951.575300,16,2810003101016,3,-1,-1,-1,1,1,1,2,-1,F41,MBD005,-1,-1,-1,2,2,2,1,2,1

In [48]:
joined.describe

<bound method NDFrame.describe of          DUID  PID    DUPERSID  PANEL  DATAYEAR FAMID31 FAMID42 FAMID53  \
0     2810003  101  2810003101     28      2024       A       A       A
1     2810013  101  2810013101     28      2024       A       A       A
2     2810035  101  2810035101     28      2024       A       A       A
3     2810045  102  2810045102     28      2024       B       B       B
4     2810048  101  2810048101     28      2024       B       B       B
...       ...  ...         ...    ...       ...     ...     ...     ...
1894  2930389  101  2930389101     29      2024       A       A       A
1895  2930389  102  2930389102     29      2024       A       A       A
1896  2930398  101  2930398101     29      2024       A       A       A
1897  2930398  102  2930398102     29      2024       A       A       A
1898  2930408  101  2930408101     29      2024       A       A       A

     FAMID24 FAMIDYR CPSFAMID  FCSZ1231  FCRP1231 RULETR31 RULETR42 RULETR53  \
0          A       A        A         1         1        A        A        A
1          A       A        A         6         0        A        A        A
2          A       A        A         1         1        A        A        A
3          B       B        B         1         1        B        B        B
4          B       B        B         1         1        B        B        B
...      ...     ...      ...       ...       ...      ...      ...      ...
1894       A       A        A        -1         1        A        A        A
1895       A       A        A        -1         0        A        A        A
1896       A       A        A         4         1        A        A        A
1897       A       A        A         4         0        A        A        A
1898       A       A        A         2         1        A        A        A

     RULETR24  RUSIZE31  RUSIZE42  RUSIZE53  RUSIZE24  RUCLAS31  RUCLAS42  \
0           A         1         1         1         1         1         1
1           A         6         6         6         6         1         1
2           A         1         1         1         1         1         1
3           B         1         1         1         2         2         1
4           B         1         1         1         2         1         1
...       ...       ...       ...       ...       ...       ...       ...
1894        A         3         4         4         4         1         1
1895        A         3         4         4         4         1         1
1896        A         4         4         4         4         1         1
1897        A         4         4         4         4         1         1
1898        A         2         2         2         2         1         1

      RUCLAS53  RUCLAS24  FAMSZE31  FAMSZE42  FAMSZE53  FAMSZE24  FMRS1231  \
0            1         1         1         1         1         1         1
1            1         1         6         6         6         6         1
2            1         1         1         1         1         1         1
3            1         1         1         1         1         2         1
4            1         1         1         1         1         2         1
...        ...       ...       ...       ...       ...       ...       ...
1894         1         1         3         4         4         4         0
1895         1         1         3         4         4         4         0
1896         1         1         4         4         4         4         1
1897         1         1         4         4         4         4         1
1898         1         1         2         2         2         2         1

      FAMS1231  FAMSZEYR  FAMRFPYR  REGION31  REGION42  REGION53  REGION24  \
0            1         1         1         3         4         4         4
1            6         6         0         4         4         4         4
2            1         1         1         1         1         1         1
3            1         1         1         1         1         1         1
4            1         1         1         4         4         4         4
...        ...       ...       ...       ...       ...       ...       ...
1894        -1         4         1         3         3         3         3
1895        -1         4         0         3         3         3         3
1896         4         4         1         3         3         3         3
1897         4         4         0         3         3         3         3
1898         2         2         1         2         2         2         2

      REFPRS31  REFPRS42  REFPRS53  REFPRS24  RESP31  RESP42  RESP53  RESP24  \
0          101       101       101       101       1       1       1       1
1          102       102       102       102       1       1       1       1
2          101       101       101       101       1       1       1       1
3          102       102       102       102       1       1       1       1
4          101       101       101       101       1       1       1       1
...        ...       ...       ...       ...     ...     ...     ...     ...
1894       101       101       101       101       1       1       2       2
1895       101       101       101       101       2       2       1       1
1896       101       101       101       101       1       1       1       1
1897       101       101       101       101       2       2       2       2
1898       101       101       101       101       1       1       1       1

      PROXY31  PROXY42  PROXY53  PROXY24  INTVLANG  INTVTYPE31  INTVTYPE42  \
0           1        1        1        1         1           1           2
1           1        1        1        1         1           3           2
2           1        1        1        1         1           1           1
3           1        1        1        1         1           1           1
4           1        1        1        1         1           1           1
...       ...      ...      ...      ...       ...         ...         ...
1894        1        1        1        1         1           1           1
1895        1        1        1        1         1           1           1
1896        1        1        1        1         1           1           1
1897        1        1        1        1         1           1           1
1898        1        1        1        1         1           1           1

      INTVTYPE53  BEGRFM31  BEGRFY31  ENDRFM31  ENDRFY31  BEGRFM42  BEGRFY42  \
0              2         8      2023         2      2024         2      2024
1              2         9      2023         4      2024         4      2024
2              1         9      2023         4      2024         4      2024
3              3         7      2023         2      2024         2      2024
4              1         9      2023         3      2024         3      2024
...          ...       ...       ...       ...       ...       ...       ...
1894           1         1      2024         2      2024         2      2024
1895           1         1      2024         2      2024         2      2024
1896           3         1      2024         4      2024         4      2024
1897           3         1      2024         4      2024         4      2024
1898           1         1      2024         2      2024         2      2024

      ENDRFM42  ENDRFY42  BEGRFM53  BEGRFY53  ENDRFM53  ENDRFY53  ENDRFM24  \
0           11      2024        11      2024        12      2024        12
1           10      2024        10      2024        12      2024        12
2            8      2024         8      2024        12      2024        12
3            7      2024         7      2024        12      2024        12
4            8      2024         8      2024        12      2024        12
...        ...       ...       ...       ...       ...       ...       ...
1894         9      2024         9      2024         2      2025        12
1895         9      2024         9      2024         2      2025        12
1896        10      2024        10      2024         3      2025        12
1897        10      2024        10      2024         3      2025        12
1898        10      2024        10      2024         2      2025        12

      ENDRFY24  KEYNESS  INSCOP31  INSCOP42  INSCOP53  INSCOP24  INSC1231  \
0         2024        1         1         1         1         1         1
1         2024        1         1         1         1         1         1
2         2024        1         1         1         1         1         1
3         2024        1         1         1         1         1         1
4         2024        1         1         1         1         1         1
...        ...      ...       ...       ...       ...       ...       ...
1894      2024        1         1         1         1         1         1
1895      2024        1         1         1         1         1         1
1896      2024        1         1         1         1         1         1
1897      2024        1         1         1         1         1         1
1898      2024        1         1         1         1         1         1

      INSCOPE  ELGRND31  ELGRND42  ELGRND53  ELGRND24  PSTATS31  PSTATS42  \
0           1         1         1         1         1        11        11
1           1         1         1         1         1        11        11
2           1         1         1         1         1        11        11
3           1         1         1         1         1        41        11
4           1         1         1         1         1        11        11
...       ...       ...       ...       ...       ...       ...       ...
1894        1         1         1         1         1        11        11
1895        1         1         1         1         1        11        11
1896        1         1         1         1         1        11        11
1897        1         1         1         1         1        11        11
1898        1         1         1         1         1        11        11

      PSTATS53  RURSLT31  RURSLT42  RURSLT53  AGE31X  AGE42X  AGE53X  AGE24X  \
0           11        60        60        60      66      67      67      67
1           11        60        60        60      37      38      38      38
2           11        60        60        60      62      62      63      63
3           11        60        60        60      32      33      33      33
4           11        60        60        60      27      28      28      28
...        ...       ...       ...       ...     ...     ...     ...     ...
1894        11        60        60        60      49      49      50      49
1895        11        60        60        60      50      50      51      51
1896        11        60        60        60      41      41      42      42
1897        11        60        60        60      42      42      43      42
1898        11        60        60        60      72      73      73      73

      AGELAST  DOBMM  DOBYY  SEX  RACEV1X  RACEV2X  RACEAX  RACEBX  RACEWX  \
0          67      3   1957    2        1        1       3       3       1
1          38      4   1986    2        1        1       3       3       1
2          63      8   1961    2        1        1       3       3       1
3          33      5   1991    2        1        1       3       3       1
4          28      3   1996    1        1        1       3       3       1
...       ...    ...    ...  ...      ...      ...     ...     ...     ...
1894       49      2   1975    1        1        1       3       3       1
1895       51     10   1973    2        6       12       2       3       2
1896       42     12   1982    2        1        1       3       3       1
1897       42      3   1982    1        1        1       3       3       1
1898       73      3   1951    2        1        1       3       3       1

      RACETHX  HISPANX  HISPNCAT  MARRY31X  MARRY42X  MARRY53X  MARRY24X  \
0           2        2         9         2         2         2         2
1           2        2         9         1         1         1         1
2           2        2         9         3         3         3         3
3           2        2         9         5         5         5         5
4           2        2         9         3         3         3         3
...       ...      ...       ...       ...       ...       ...       ...
1894        2        2         9         1         1         1         1
1895        5        2         9         1         1         1         1
1896        2        2         9         1         1         1         1
1897        2        2         9         1         1         1         1
1898        2        2         9         1         1         1         1

      SPOUID31  SPOUID42  SPOUID53  SPOUID24  SPOUIN31  SPOUIN42  SPOUIN53  \
0          995       995       995       995         2         2         2
1          102       102       102       102         1         1         1
2          995       995       995       995         2         2         2
3          995       995       995       995         2         2         2
4          995       995       995       995         2         2         2
...        ...       ...       ...       ...       ...       ...       ...
1894       102       102       102       102         1         1         1
1895       101       101       101       101         1         1         1
1896       102       102       102       102         1         1         1
1897       101       101       101       101         1         1         1
1898       102       102       102       102         1         1         1

      SPOUIN24  EDUCYR  HIDEG  FTSTU31X  FTSTU42X  FTSTU53X  FTSTU24X  \
0            2      12      3        -1        -1        -1        -1
1            1      14      7        -1        -1        -1        -1
2            2      17      5        -1        -1        -1        -1
3            2      12      3        -1        -1        -1        -1
4            2      12      3        -1        -1        -1        -1
...        ...     ...    ...       ...       ...       ...       ...
1894         1      16      4        -1        -1        -1        -1
1895         1      16      4        -1        -1        -1        -1
1896         1      17      6        -1        -1        -1        -1
1897         1      12      3        -1        -1        -1        -1
1898         1      17      5        -1        -1        -1        -1

      ACTDTY31  ACTDTY42  ACTDTY53  EVERSERVED  REFRL31X  REFRL42X  REFRL53X  \
0            4         4         4           2         1         1         1
1            2         2         2           2         2         2         2
2            4         4         4           2         1         1         1
3            2         2         2           2         1         1         1
4            2         2         2           1         1         1         1
...        ...       ...       ...         ...       ...       ...       ...
1894         2         2         2           2         1         1         1
1895         2         2         2           2         2         2         2
1896         2         2         2           2         1         1         1
1897         2         2         2           2         2         2         2
1898         4         4         4           2         1         1         1

      REFRL24X  OTHLGSPK  WHTLGSPK  HWELLSPK  BORNUSA  YRSINUS  MOPID31X  \
0            1         2        -1        -1        1       -1        -1
1            2         2        -1        -1        1       -1        -1
2            1         2        -1        -1        1       -1        -1
3            1         2        -1        -1        1       -1        -1
4            1         2        -1        -1        1       -1        -1
...        ...       ...       ...       ...      ...      ...       ...
1894         1         2        -1        -1        2        5        -1
1895         2         2        -1        -1        1       -1        -1
1896         1         2        -1        -1        1       -1        -1
1897         2         2        -1        -1        1       -1        -1
1898         1         2        -1        -1        1       -1        -1

      MOPID42X  MOPID53X  DAPID31X  DAPID42X  DAPID53X  HIBPDX  HIBPAGED  \
0           -1        -1        -1        -1        -1       2        -1
1           -1        -1        -1        -1        -1       2        -1
2           -1        -1        -1        -1        -1       1        46
3           -1        -1        -1        -1        -1       2        -1
4           -1        -1        -1        -1        -1       2        -1
...        ...       ...       ...       ...       ...     ...       ...
1894        -1        -1        -1        -1        -1       1        45
1895        -1        -1        -1        -1        -1       1        30
1896        -1        -1        -1        -1        -1       2        -1
1897        -1        -1        -1        -1        -1       1        35
1898        -1        -1        -1        -1        -1       2        -1

      BPMLDX  CHDDX  CHDAGED  ANGIDX  ANGIAGED  MIDX  MIAGED  OHRTDX  \
0         -1      2       -1       2        -1     2      -1       1
1         -1      2       -1       2        -1     2      -1       2
2          1      2       -1       2        -1     2      -1       2
3         -1      2       -1       2        -1     2      -1       2
4         -1      2       -1       2        -1     2      -1       2
...      ...    ...      ...     ...       ...   ...     ...     ...
1894       1      2       -1       2        -1     2      -1       2
1895       1      2       -1       2        -1     2      -1       2
1896      -1      2       -1       2        -1     2      -1       2
1897       1      2       -1       2        -1     2      -1       2
1898      -1      1       68       2        -1     2      -1       2

      OHRTAGED  OHRTTYPE  STRKDX  STRKAGED  EMPHDX  EMPHAGED  CHBRON31  \
0           30         6       2        -1       2        -1         2
1           -1        -1       2        -1       2        -1         2
2           -1        -1       2        -1       1        61         2
3           -1        -1       2        -1       2        -1         2
4           -1        -1       2        -1       2        -1         2
...        ...       ...     ...       ...     ...       ...       ...
1894        -1        -1       2        -1       2        -1         2
1895        -1        -1       2        -1       2        -1         2
1896        -1        -1       2        -1       2        -1         2
1897        -1        -1       2        -1       2        -1         2
1898        -1        -1       2        -1       2        -1         2

      CHOLDX  CHOLAGED  CANCERDX  CABLADDR  CABREAST  CACERVIX  CACOLON  \
0          1        65         2        -1        -1        -1       -1
1          2        -1         2        -1        -1        -1       -1
2          1        59         2        -1        -1        -1       -1
3          2        -1         2        -1        -1        -1       -1
4          2        -1         2        -1        -1        -1       -1
...      ...       ...       ...       ...       ...       ...      ...
1894       1        48         2        -1        -1        -1       -1
1895       1        35         2        -1        -1        -1       -1
1896       2        -1         2        -1        -1        -1       -1
1897       1        35         2        -1        -1        -1       -1
1898       2        -1         2        -1        -1        -1       -1

      CALUNG  CALYMPH  CAMELANO  CAOTHER  CAPROSTA  CASKINNM  CASKINDK  \
0         -1       -1        -1       -1        -1        -1        -1
1         -1       -1        -1       -1        -1        -1        -1
2         -1       -1        -1       -1        -1        -1        -1

In [49]:
joined['DUPERSID'].duplicated().sum()

np.int64(0)

In [ ]:
# saving checkpoint after merging (step 3 in phase 2 instructions)
joined.to_csv('F41_merged.csv', index = False)